//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace in24seven.timeRef {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="TimeServiceSoap", Namespace="http://24sevenOffice.com/webservices")]
    public partial class TimeService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetTimeSettingsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetWorkTypeListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetProjectListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetProjectDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveHourOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteHourOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddCostOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCostsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetHoursOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSalaryTypesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetHoursForApprovalOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public TimeService() {
            this.Url = global::in24seven.Properties.Settings.Default.in24seven_timeRef_TimeService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetTimeSettingsCompletedEventHandler GetTimeSettingsCompleted;
        
        /// <remarks/>
        public event GetWorkTypeListCompletedEventHandler GetWorkTypeListCompleted;
        
        /// <remarks/>
        public event GetProjectListCompletedEventHandler GetProjectListCompleted;
        
        /// <remarks/>
        public event GetProjectDataCompletedEventHandler GetProjectDataCompleted;
        
        /// <remarks/>
        public event SaveHourCompletedEventHandler SaveHourCompleted;
        
        /// <remarks/>
        public event DeleteHourCompletedEventHandler DeleteHourCompleted;
        
        /// <remarks/>
        public event AddCostCompletedEventHandler AddCostCompleted;
        
        /// <remarks/>
        public event GetCostsCompletedEventHandler GetCostsCompleted;
        
        /// <remarks/>
        public event GetHoursCompletedEventHandler GetHoursCompleted;
        
        /// <remarks/>
        public event GetSalaryTypesCompletedEventHandler GetSalaryTypesCompleted;
        
        /// <remarks/>
        public event GetHoursForApprovalCompletedEventHandler GetHoursForApprovalCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://24sevenOffice.com/webservices/GetTimeSettings", RequestNamespace="http://24sevenOffice.com/webservices", ResponseNamespace="http://24sevenOffice.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public KeyValuePair[] GetTimeSettings() {
            object[] results = this.Invoke("GetTimeSettings", new object[0]);
            return ((KeyValuePair[])(results[0]));
        }
        
        /// <remarks/>
        public void GetTimeSettingsAsync() {
            this.GetTimeSettingsAsync(null);
        }
        
        /// <remarks/>
        public void GetTimeSettingsAsync(object userState) {
            if ((this.GetTimeSettingsOperationCompleted == null)) {
                this.GetTimeSettingsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTimeSettingsOperationCompleted);
            }
            this.InvokeAsync("GetTimeSettings", new object[0], this.GetTimeSettingsOperationCompleted, userState);
        }
        
        private void OnGetTimeSettingsOperationCompleted(object arg) {
            if ((this.GetTimeSettingsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTimeSettingsCompleted(this, new GetTimeSettingsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://24sevenOffice.com/webservices/GetWorkTypeList", RequestNamespace="http://24sevenOffice.com/webservices", ResponseNamespace="http://24sevenOffice.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public WorkType[] GetWorkTypeList(WorkTypeSearch Wts) {
            object[] results = this.Invoke("GetWorkTypeList", new object[] {
                        Wts});
            return ((WorkType[])(results[0]));
        }
        
        /// <remarks/>
        public void GetWorkTypeListAsync(WorkTypeSearch Wts) {
            this.GetWorkTypeListAsync(Wts, null);
        }
        
        /// <remarks/>
        public void GetWorkTypeListAsync(WorkTypeSearch Wts, object userState) {
            if ((this.GetWorkTypeListOperationCompleted == null)) {
                this.GetWorkTypeListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetWorkTypeListOperationCompleted);
            }
            this.InvokeAsync("GetWorkTypeList", new object[] {
                        Wts}, this.GetWorkTypeListOperationCompleted, userState);
        }
        
        private void OnGetWorkTypeListOperationCompleted(object arg) {
            if ((this.GetWorkTypeListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetWorkTypeListCompleted(this, new GetWorkTypeListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://24sevenOffice.com/webservices/GetProjectList", RequestNamespace="http://24sevenOffice.com/webservices", ResponseNamespace="http://24sevenOffice.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Project[] GetProjectList(ProjectSearch Ps) {
            object[] results = this.Invoke("GetProjectList", new object[] {
                        Ps});
            return ((Project[])(results[0]));
        }
        
        /// <remarks/>
        public void GetProjectListAsync(ProjectSearch Ps) {
            this.GetProjectListAsync(Ps, null);
        }
        
        /// <remarks/>
        public void GetProjectListAsync(ProjectSearch Ps, object userState) {
            if ((this.GetProjectListOperationCompleted == null)) {
                this.GetProjectListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProjectListOperationCompleted);
            }
            this.InvokeAsync("GetProjectList", new object[] {
                        Ps}, this.GetProjectListOperationCompleted, userState);
        }
        
        private void OnGetProjectListOperationCompleted(object arg) {
            if ((this.GetProjectListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetProjectListCompleted(this, new GetProjectListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://24sevenOffice.com/webservices/GetProjectData", RequestNamespace="http://24sevenOffice.com/webservices", ResponseNamespace="http://24sevenOffice.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ProjectData GetProjectData(ProjectDataSearch Pds) {
            object[] results = this.Invoke("GetProjectData", new object[] {
                        Pds});
            return ((ProjectData)(results[0]));
        }
        
        /// <remarks/>
        public void GetProjectDataAsync(ProjectDataSearch Pds) {
            this.GetProjectDataAsync(Pds, null);
        }
        
        /// <remarks/>
        public void GetProjectDataAsync(ProjectDataSearch Pds, object userState) {
            if ((this.GetProjectDataOperationCompleted == null)) {
                this.GetProjectDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProjectDataOperationCompleted);
            }
            this.InvokeAsync("GetProjectData", new object[] {
                        Pds}, this.GetProjectDataOperationCompleted, userState);
        }
        
        private void OnGetProjectDataOperationCompleted(object arg) {
            if ((this.GetProjectDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetProjectDataCompleted(this, new GetProjectDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://24sevenOffice.com/webservices/SaveHour", RequestNamespace="http://24sevenOffice.com/webservices", ResponseNamespace="http://24sevenOffice.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long SaveHour(Hour Hour) {
            object[] results = this.Invoke("SaveHour", new object[] {
                        Hour});
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public void SaveHourAsync(Hour Hour) {
            this.SaveHourAsync(Hour, null);
        }
        
        /// <remarks/>
        public void SaveHourAsync(Hour Hour, object userState) {
            if ((this.SaveHourOperationCompleted == null)) {
                this.SaveHourOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveHourOperationCompleted);
            }
            this.InvokeAsync("SaveHour", new object[] {
                        Hour}, this.SaveHourOperationCompleted, userState);
        }
        
        private void OnSaveHourOperationCompleted(object arg) {
            if ((this.SaveHourCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveHourCompleted(this, new SaveHourCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://24sevenOffice.com/webservices/DeleteHour", RequestNamespace="http://24sevenOffice.com/webservices", ResponseNamespace="http://24sevenOffice.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool DeleteHour(Hour Hour) {
            object[] results = this.Invoke("DeleteHour", new object[] {
                        Hour});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteHourAsync(Hour Hour) {
            this.DeleteHourAsync(Hour, null);
        }
        
        /// <remarks/>
        public void DeleteHourAsync(Hour Hour, object userState) {
            if ((this.DeleteHourOperationCompleted == null)) {
                this.DeleteHourOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteHourOperationCompleted);
            }
            this.InvokeAsync("DeleteHour", new object[] {
                        Hour}, this.DeleteHourOperationCompleted, userState);
        }
        
        private void OnDeleteHourOperationCompleted(object arg) {
            if ((this.DeleteHourCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteHourCompleted(this, new DeleteHourCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://24sevenOffice.com/webservices/AddCost", RequestNamespace="http://24sevenOffice.com/webservices", ResponseNamespace="http://24sevenOffice.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AddCost(Cost cost) {
            this.Invoke("AddCost", new object[] {
                        cost});
        }
        
        /// <remarks/>
        public void AddCostAsync(Cost cost) {
            this.AddCostAsync(cost, null);
        }
        
        /// <remarks/>
        public void AddCostAsync(Cost cost, object userState) {
            if ((this.AddCostOperationCompleted == null)) {
                this.AddCostOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddCostOperationCompleted);
            }
            this.InvokeAsync("AddCost", new object[] {
                        cost}, this.AddCostOperationCompleted, userState);
        }
        
        private void OnAddCostOperationCompleted(object arg) {
            if ((this.AddCostCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddCostCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://24sevenOffice.com/webservices/GetCosts", RequestNamespace="http://24sevenOffice.com/webservices", ResponseNamespace="http://24sevenOffice.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Cost[] GetCosts(CostSearchParameters costSearchParameters) {
            object[] results = this.Invoke("GetCosts", new object[] {
                        costSearchParameters});
            return ((Cost[])(results[0]));
        }
        
        /// <remarks/>
        public void GetCostsAsync(CostSearchParameters costSearchParameters) {
            this.GetCostsAsync(costSearchParameters, null);
        }
        
        /// <remarks/>
        public void GetCostsAsync(CostSearchParameters costSearchParameters, object userState) {
            if ((this.GetCostsOperationCompleted == null)) {
                this.GetCostsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCostsOperationCompleted);
            }
            this.InvokeAsync("GetCosts", new object[] {
                        costSearchParameters}, this.GetCostsOperationCompleted, userState);
        }
        
        private void OnGetCostsOperationCompleted(object arg) {
            if ((this.GetCostsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCostsCompleted(this, new GetCostsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://24sevenOffice.com/webservices/GetHours", RequestNamespace="http://24sevenOffice.com/webservices", ResponseNamespace="http://24sevenOffice.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Hour[] GetHours(HourSearch hs) {
            object[] results = this.Invoke("GetHours", new object[] {
                        hs});
            return ((Hour[])(results[0]));
        }
        
        /// <remarks/>
        public void GetHoursAsync(HourSearch hs) {
            this.GetHoursAsync(hs, null);
        }
        
        /// <remarks/>
        public void GetHoursAsync(HourSearch hs, object userState) {
            if ((this.GetHoursOperationCompleted == null)) {
                this.GetHoursOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetHoursOperationCompleted);
            }
            this.InvokeAsync("GetHours", new object[] {
                        hs}, this.GetHoursOperationCompleted, userState);
        }
        
        private void OnGetHoursOperationCompleted(object arg) {
            if ((this.GetHoursCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetHoursCompleted(this, new GetHoursCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://24sevenOffice.com/webservices/GetSalaryTypes", RequestNamespace="http://24sevenOffice.com/webservices", ResponseNamespace="http://24sevenOffice.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SalaryType[] GetSalaryTypes() {
            object[] results = this.Invoke("GetSalaryTypes", new object[0]);
            return ((SalaryType[])(results[0]));
        }
        
        /// <remarks/>
        public void GetSalaryTypesAsync() {
            this.GetSalaryTypesAsync(null);
        }
        
        /// <remarks/>
        public void GetSalaryTypesAsync(object userState) {
            if ((this.GetSalaryTypesOperationCompleted == null)) {
                this.GetSalaryTypesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSalaryTypesOperationCompleted);
            }
            this.InvokeAsync("GetSalaryTypes", new object[0], this.GetSalaryTypesOperationCompleted, userState);
        }
        
        private void OnGetSalaryTypesOperationCompleted(object arg) {
            if ((this.GetSalaryTypesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSalaryTypesCompleted(this, new GetSalaryTypesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://24sevenOffice.com/webservices/GetHoursForApproval", RequestNamespace="http://24sevenOffice.com/webservices", ResponseNamespace="http://24sevenOffice.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Hour[] GetHoursForApproval(ApprovalSearchParameters approvalSearchParameters) {
            object[] results = this.Invoke("GetHoursForApproval", new object[] {
                        approvalSearchParameters});
            return ((Hour[])(results[0]));
        }
        
        /// <remarks/>
        public void GetHoursForApprovalAsync(ApprovalSearchParameters approvalSearchParameters) {
            this.GetHoursForApprovalAsync(approvalSearchParameters, null);
        }
        
        /// <remarks/>
        public void GetHoursForApprovalAsync(ApprovalSearchParameters approvalSearchParameters, object userState) {
            if ((this.GetHoursForApprovalOperationCompleted == null)) {
                this.GetHoursForApprovalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetHoursForApprovalOperationCompleted);
            }
            this.InvokeAsync("GetHoursForApproval", new object[] {
                        approvalSearchParameters}, this.GetHoursForApprovalOperationCompleted, userState);
        }
        
        private void OnGetHoursForApprovalOperationCompleted(object arg) {
            if ((this.GetHoursForApprovalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetHoursForApprovalCompleted(this, new GetHoursForApprovalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public partial class KeyValuePair {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public partial class ApprovalSearchParameters {
        
        private int contactIdField;
        
        private int projectIdField;
        
        public ApprovalSearchParameters() {
            this.contactIdField = -2147483648;
            this.projectIdField = -2147483648;
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int ContactId {
            get {
                return this.contactIdField;
            }
            set {
                this.contactIdField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int ProjectId {
            get {
                return this.projectIdField;
            }
            set {
                this.projectIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public partial class SalaryType {
        
        private int idField;
        
        private string nameField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public partial class HourSearch {
        
        private HourStatus statusField;
        
        private int contactIdField;
        
        private int projectIdField;
        
        private bool includeSalaryTypeField;
        
        private System.DateTime startTimeField;
        
        private System.DateTime stopTimeField;
        
        public HourSearch() {
            this.statusField = HourStatus.none;
            this.includeSalaryTypeField = false;
            this.startTimeField = new System.DateTime(0);
            this.stopTimeField = new System.DateTime(0);
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(HourStatus.none)]
        public HourStatus Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public int ContactId {
            get {
                return this.contactIdField;
            }
            set {
                this.contactIdField = value;
            }
        }
        
        /// <remarks/>
        public int ProjectId {
            get {
                return this.projectIdField;
            }
            set {
                this.projectIdField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool IncludeSalaryType {
            get {
                return this.includeSalaryTypeField;
            }
            set {
                this.includeSalaryTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(System.DateTime), "0001-01-01T00:00:00")]
        public System.DateTime StartTime {
            get {
                return this.startTimeField;
            }
            set {
                this.startTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(System.DateTime), "0001-01-01T00:00:00")]
        public System.DateTime StopTime {
            get {
                return this.stopTimeField;
            }
            set {
                this.stopTimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public enum HourStatus {
        
        /// <remarks/>
        none,
        
        /// <remarks/>
        Registered,
        
        /// <remarks/>
        Locked,
        
        /// <remarks/>
        Approved,
        
        /// <remarks/>
        Rejected,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public partial class CostSearchParameters {
        
        private int projectIdField;
        
        private int contactIdField;
        
        public CostSearchParameters() {
            this.projectIdField = -2147483648;
            this.contactIdField = -2147483648;
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int ProjectId {
            get {
                return this.projectIdField;
            }
            set {
                this.projectIdField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int ContactId {
            get {
                return this.contactIdField;
            }
            set {
                this.contactIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public partial class Cost {
        
        private int idField;
        
        private System.Nullable<System.DateTime> dateRegisteredField;
        
        private System.Nullable<int> productIdField;
        
        private System.Nullable<int> supplierCompanyIdField;
        
        private System.Nullable<double> quantityField;
        
        private System.Nullable<decimal> inPriceField;
        
        private string descriptionField;
        
        private System.Nullable<int> projectIdField;
        
        private decimal priceField;
        
        private int customerIdField;
        
        private int contactIdField;
        
        public Cost() {
            this.idField = -2147483648;
            this.priceField = ((decimal)(-79228162514264337593543950335m));
            this.customerIdField = -2147483648;
            this.contactIdField = -2147483648;
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DateRegistered {
            get {
                return this.dateRegisteredField;
            }
            set {
                this.dateRegisteredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> ProductId {
            get {
                return this.productIdField;
            }
            set {
                this.productIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> SupplierCompanyId {
            get {
                return this.supplierCompanyIdField;
            }
            set {
                this.supplierCompanyIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> InPrice {
            get {
                return this.inPriceField;
            }
            set {
                this.inPriceField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> ProjectId {
            get {
                return this.projectIdField;
            }
            set {
                this.projectIdField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "-79228162514264337593543950335")]
        public decimal Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int CustomerId {
            get {
                return this.customerIdField;
            }
            set {
                this.customerIdField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int ContactId {
            get {
                return this.contactIdField;
            }
            set {
                this.contactIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public partial class Hour {
        
        private long idField;
        
        private int typeOfWorkIdField;
        
        private System.DateTime startTimeField;
        
        private System.DateTime stopTimeField;
        
        private double totalHoursField;
        
        private double totalHoursInvoiceField;
        
        private int contactIdField;
        
        private int projectIdField;
        
        private string descriptionField;
        
        private TriState lockedField;
        
        private TriState approvedField;
        
        private int approvedByField;
        
        private int projectTaskIdField;
        
        private Cost[] costsField;
        
        private bool needApprovalField;
        
        private int salaryTypeIdField;
        
        private int customerIdField;
        
        private int orderIdField;
        
        private decimal priceField;
        
        public Hour() {
            this.idField = ((long)(-9223372036854775808));
            this.typeOfWorkIdField = -2147483648;
            this.startTimeField = new System.DateTime(0);
            this.stopTimeField = new System.DateTime(0);
            this.totalHoursField = 0D;
            this.totalHoursInvoiceField = 0D;
            this.contactIdField = -2147483648;
            this.projectIdField = -2147483648;
            this.descriptionField = "";
            this.lockedField = TriState.none;
            this.approvedField = TriState.none;
            this.approvedByField = -2147483648;
            this.projectTaskIdField = -2147483648;
            this.needApprovalField = false;
            this.salaryTypeIdField = -2147483648;
            this.customerIdField = -2147483648;
            this.orderIdField = -2147483648;
            this.priceField = ((decimal)(-79228162514264337593543950335m));
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(long), "-9223372036854775808")]
        public long Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int TypeOfWorkId {
            get {
                return this.typeOfWorkIdField;
            }
            set {
                this.typeOfWorkIdField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(System.DateTime), "0001-01-01T00:00:00")]
        public System.DateTime StartTime {
            get {
                return this.startTimeField;
            }
            set {
                this.startTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(System.DateTime), "0001-01-01T00:00:00")]
        public System.DateTime StopTime {
            get {
                return this.stopTimeField;
            }
            set {
                this.stopTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(0D)]
        public double TotalHours {
            get {
                return this.totalHoursField;
            }
            set {
                this.totalHoursField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(0D)]
        public double TotalHoursInvoice {
            get {
                return this.totalHoursInvoiceField;
            }
            set {
                this.totalHoursInvoiceField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int ContactId {
            get {
                return this.contactIdField;
            }
            set {
                this.contactIdField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int ProjectId {
            get {
                return this.projectIdField;
            }
            set {
                this.projectIdField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("")]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(TriState.none)]
        public TriState Locked {
            get {
                return this.lockedField;
            }
            set {
                this.lockedField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(TriState.none)]
        public TriState Approved {
            get {
                return this.approvedField;
            }
            set {
                this.approvedField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int ApprovedBy {
            get {
                return this.approvedByField;
            }
            set {
                this.approvedByField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int ProjectTaskId {
            get {
                return this.projectTaskIdField;
            }
            set {
                this.projectTaskIdField = value;
            }
        }
        
        /// <remarks/>
        public Cost[] Costs {
            get {
                return this.costsField;
            }
            set {
                this.costsField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool NeedApproval {
            get {
                return this.needApprovalField;
            }
            set {
                this.needApprovalField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int SalaryTypeId {
            get {
                return this.salaryTypeIdField;
            }
            set {
                this.salaryTypeIdField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int CustomerId {
            get {
                return this.customerIdField;
            }
            set {
                this.customerIdField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int OrderId {
            get {
                return this.orderIdField;
            }
            set {
                this.orderIdField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "-79228162514264337593543950335")]
        public decimal Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public enum TriState {
        
        /// <remarks/>
        unknown,
        
        /// <remarks/>
        none,
        
        /// <remarks/>
        True,
        
        /// <remarks/>
        False,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public partial class Task {
        
        private int idField;
        
        private string nameField;
        
        private string descriptionField;
        
        private System.DateTime dateStartField;
        
        private System.DateTime dateStopField;
        
        private decimal overtimeField;
        
        private int parentField;
        
        private int priorityField;
        
        private int projectField;
        
        private int projectLinkField;
        
        private System.Nullable<int> statusField;
        
        private int workTypeIdField;
        
        private int estimateField;
        
        private decimal registeredField;
        
        private int[] participantsField;
        
        public Task() {
            this.idField = -2147483648;
            this.nameField = "";
            this.descriptionField = "";
            this.dateStartField = new System.DateTime(0);
            this.dateStopField = new System.DateTime(0);
            this.parentField = -2147483648;
            this.priorityField = -2147483648;
            this.projectField = -2147483648;
            this.projectLinkField = -2147483648;
            this.workTypeIdField = -2147483648;
            this.estimateField = -2147483648;
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("")]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("")]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(System.DateTime), "0001-01-01T00:00:00")]
        public System.DateTime DateStart {
            get {
                return this.dateStartField;
            }
            set {
                this.dateStartField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(System.DateTime), "0001-01-01T00:00:00")]
        public System.DateTime DateStop {
            get {
                return this.dateStopField;
            }
            set {
                this.dateStopField = value;
            }
        }
        
        /// <remarks/>
        public decimal Overtime {
            get {
                return this.overtimeField;
            }
            set {
                this.overtimeField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int Parent {
            get {
                return this.parentField;
            }
            set {
                this.parentField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int Priority {
            get {
                return this.priorityField;
            }
            set {
                this.priorityField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int Project {
            get {
                return this.projectField;
            }
            set {
                this.projectField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int ProjectLink {
            get {
                return this.projectLinkField;
            }
            set {
                this.projectLinkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int WorkTypeId {
            get {
                return this.workTypeIdField;
            }
            set {
                this.workTypeIdField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int Estimate {
            get {
                return this.estimateField;
            }
            set {
                this.estimateField = value;
            }
        }
        
        /// <remarks/>
        public decimal Registered {
            get {
                return this.registeredField;
            }
            set {
                this.registeredField = value;
            }
        }
        
        /// <remarks/>
        public int[] Participants {
            get {
                return this.participantsField;
            }
            set {
                this.participantsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public partial class ProjectData {
        
        private Project projectField;
        
        private WorkType[] workTypesField;
        
        private Task[] tasksField;
        
        /// <remarks/>
        public Project Project {
            get {
                return this.projectField;
            }
            set {
                this.projectField = value;
            }
        }
        
        /// <remarks/>
        public WorkType[] WorkTypes {
            get {
                return this.workTypesField;
            }
            set {
                this.workTypesField = value;
            }
        }
        
        /// <remarks/>
        public Task[] Tasks {
            get {
                return this.tasksField;
            }
            set {
                this.tasksField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public partial class Project {
        
        private int idField;
        
        private bool enabledField;
        
        private string nameField;
        
        private string rawNameField;
        
        private ProjectNameType nameDisplayField;
        
        private bool quickListedField;
        
        private System.DateTime dateChangedField;
        
        private System.DateTime dateStartField;
        
        private System.DateTime dateStopField;
        
        private int customerIdField;
        
        private string customerNameField;
        
        private int ownerField;
        
        private int pipelineField;
        
        private int typeIdField;
        
        private string typeNameField;
        
        private int statusIdField;
        
        private string statusNameField;
        
        private TriState needApprovalField;
        
        private bool multiCustomerField;
        
        private string descriptionField;
        
        private int workTypeIdField;
        
        private string workTypeNameField;
        
        private TimeRegType timeRegField;
        
        private short versionField;
        
        private TriState isFoldersAddedField;
        
        private int[] participantsField;
        
        public Project() {
            this.idField = -2147483648;
            this.enabledField = false;
            this.nameField = "";
            this.rawNameField = "";
            this.quickListedField = true;
            this.dateChangedField = new System.DateTime(0);
            this.dateStartField = new System.DateTime(0);
            this.dateStopField = new System.DateTime(0);
            this.customerIdField = -2147483648;
            this.customerNameField = "";
            this.ownerField = -2147483648;
            this.pipelineField = -2147483648;
            this.typeIdField = -2147483648;
            this.typeNameField = "";
            this.statusIdField = -2147483648;
            this.statusNameField = "";
            this.needApprovalField = TriState.none;
            this.multiCustomerField = false;
            this.descriptionField = "";
            this.workTypeIdField = -2147483648;
            this.workTypeNameField = "";
            this.versionField = ((short)(-32768));
            this.isFoldersAddedField = TriState.none;
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Enabled {
            get {
                return this.enabledField;
            }
            set {
                this.enabledField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("")]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("")]
        public string RawName {
            get {
                return this.rawNameField;
            }
            set {
                this.rawNameField = value;
            }
        }
        
        /// <remarks/>
        public ProjectNameType NameDisplay {
            get {
                return this.nameDisplayField;
            }
            set {
                this.nameDisplayField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool QuickListed {
            get {
                return this.quickListedField;
            }
            set {
                this.quickListedField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(System.DateTime), "0001-01-01T00:00:00")]
        public System.DateTime DateChanged {
            get {
                return this.dateChangedField;
            }
            set {
                this.dateChangedField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(System.DateTime), "0001-01-01T00:00:00")]
        public System.DateTime DateStart {
            get {
                return this.dateStartField;
            }
            set {
                this.dateStartField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(System.DateTime), "0001-01-01T00:00:00")]
        public System.DateTime DateStop {
            get {
                return this.dateStopField;
            }
            set {
                this.dateStopField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int CustomerId {
            get {
                return this.customerIdField;
            }
            set {
                this.customerIdField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("")]
        public string CustomerName {
            get {
                return this.customerNameField;
            }
            set {
                this.customerNameField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int Owner {
            get {
                return this.ownerField;
            }
            set {
                this.ownerField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int Pipeline {
            get {
                return this.pipelineField;
            }
            set {
                this.pipelineField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int TypeId {
            get {
                return this.typeIdField;
            }
            set {
                this.typeIdField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("")]
        public string TypeName {
            get {
                return this.typeNameField;
            }
            set {
                this.typeNameField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int StatusId {
            get {
                return this.statusIdField;
            }
            set {
                this.statusIdField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("")]
        public string StatusName {
            get {
                return this.statusNameField;
            }
            set {
                this.statusNameField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(TriState.none)]
        public TriState NeedApproval {
            get {
                return this.needApprovalField;
            }
            set {
                this.needApprovalField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool MultiCustomer {
            get {
                return this.multiCustomerField;
            }
            set {
                this.multiCustomerField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("")]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int WorkTypeId {
            get {
                return this.workTypeIdField;
            }
            set {
                this.workTypeIdField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("")]
        public string WorkTypeName {
            get {
                return this.workTypeNameField;
            }
            set {
                this.workTypeNameField = value;
            }
        }
        
        /// <remarks/>
        public TimeRegType TimeReg {
            get {
                return this.timeRegField;
            }
            set {
                this.timeRegField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(short), "-32768")]
        public short Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(TriState.none)]
        public TriState IsFoldersAdded {
            get {
                return this.isFoldersAddedField;
            }
            set {
                this.isFoldersAddedField = value;
            }
        }
        
        /// <remarks/>
        public int[] Participants {
            get {
                return this.participantsField;
            }
            set {
                this.participantsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public enum ProjectNameType {
        
        /// <remarks/>
        unknown,
        
        /// <remarks/>
        Plain,
        
        /// <remarks/>
        Company_Project,
        
        /// <remarks/>
        Project_Company,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public enum TimeRegType {
        
        /// <remarks/>
        unknown,
        
        /// <remarks/>
        WorkType,
        
        /// <remarks/>
        Task,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public partial class WorkType {
        
        private int idField;
        
        private string nameField;
        
        private string descriptionField;
        
        private bool invoiceableField;
        
        private decimal priceField;
        
        private int productIdField;
        
        public WorkType() {
            this.priceField = ((decimal)(-79228162514264337593543950335m));
            this.productIdField = -2147483648;
        }
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public bool Invoiceable {
            get {
                return this.invoiceableField;
            }
            set {
                this.invoiceableField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "-79228162514264337593543950335")]
        public decimal Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int ProductId {
            get {
                return this.productIdField;
            }
            set {
                this.productIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public partial class ProjectDataSearch {
        
        private int projectIdField;
        
        private int contactIdField;
        
        private bool projectOnlyField;
        
        public ProjectDataSearch() {
            this.contactIdField = -2147483648;
            this.projectOnlyField = false;
        }
        
        /// <remarks/>
        public int ProjectId {
            get {
                return this.projectIdField;
            }
            set {
                this.projectIdField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int ContactId {
            get {
                return this.contactIdField;
            }
            set {
                this.contactIdField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool ProjectOnly {
            get {
                return this.projectOnlyField;
            }
            set {
                this.projectOnlyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public partial class ProjectSearch {
        
        private bool myProjectsField;
        
        private bool allOpenProjectsField;
        
        private int customerIdField;
        
        private string searchField;
        
        private System.DateTime changedAfterField;
        
        private System.DateTime startedAfterField;
        
        private System.DateTime startedBeforeField;
        
        public ProjectSearch() {
            this.myProjectsField = false;
            this.allOpenProjectsField = false;
            this.customerIdField = -2147483648;
            this.searchField = "";
            this.changedAfterField = new System.DateTime(0);
            this.startedAfterField = new System.DateTime(0);
            this.startedBeforeField = new System.DateTime(0);
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool MyProjects {
            get {
                return this.myProjectsField;
            }
            set {
                this.myProjectsField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool AllOpenProjects {
            get {
                return this.allOpenProjectsField;
            }
            set {
                this.allOpenProjectsField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int CustomerId {
            get {
                return this.customerIdField;
            }
            set {
                this.customerIdField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("")]
        public string Search {
            get {
                return this.searchField;
            }
            set {
                this.searchField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(System.DateTime), "0001-01-01T00:00:00")]
        public System.DateTime ChangedAfter {
            get {
                return this.changedAfterField;
            }
            set {
                this.changedAfterField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(System.DateTime), "0001-01-01T00:00:00")]
        public System.DateTime StartedAfter {
            get {
                return this.startedAfterField;
            }
            set {
                this.startedAfterField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(System.DateTime), "0001-01-01T00:00:00")]
        public System.DateTime StartedBefore {
            get {
                return this.startedBeforeField;
            }
            set {
                this.startedBeforeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public partial class WorkTypeSearch {
        
        private TriState activeField;
        
        private int projectIdField;
        
        public WorkTypeSearch() {
            this.activeField = TriState.none;
            this.projectIdField = -2147483648;
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(TriState.none)]
        public TriState Active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int ProjectId {
            get {
                return this.projectIdField;
            }
            set {
                this.projectIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetTimeSettingsCompletedEventHandler(object sender, GetTimeSettingsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTimeSettingsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTimeSettingsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public KeyValuePair[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((KeyValuePair[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetWorkTypeListCompletedEventHandler(object sender, GetWorkTypeListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetWorkTypeListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetWorkTypeListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WorkType[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WorkType[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetProjectListCompletedEventHandler(object sender, GetProjectListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetProjectListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetProjectListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Project[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Project[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetProjectDataCompletedEventHandler(object sender, GetProjectDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetProjectDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetProjectDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ProjectData Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ProjectData)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void SaveHourCompletedEventHandler(object sender, SaveHourCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveHourCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveHourCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public long Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((long)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void DeleteHourCompletedEventHandler(object sender, DeleteHourCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteHourCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteHourCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void AddCostCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetCostsCompletedEventHandler(object sender, GetCostsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCostsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCostsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Cost[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Cost[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetHoursCompletedEventHandler(object sender, GetHoursCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetHoursCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetHoursCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Hour[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Hour[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetSalaryTypesCompletedEventHandler(object sender, GetSalaryTypesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSalaryTypesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSalaryTypesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SalaryType[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SalaryType[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetHoursForApprovalCompletedEventHandler(object sender, GetHoursForApprovalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetHoursForApprovalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetHoursForApprovalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Hour[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Hour[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591