//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace in24seven.companyRef {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CompanyServiceSoap", Namespace="http://24sevenOffice.com/webservices")]
    public partial class CompanyService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback DeleteRelationsOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteCompaniesOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveRelationsOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteMapsOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveMapsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCompaniesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCategoriesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCustomerCategoriesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetIndustriesOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveCustomerCategoriesOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteCustomerCategoriesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCustomerCategoryTreeOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveCompaniesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetStatusesOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CompanyService() {
            this.Url = global::in24seven.Properties.Settings.Default.in24seven_companyRef_CompanyService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event DeleteRelationsCompletedEventHandler DeleteRelationsCompleted;
        
        /// <remarks/>
        public event DeleteCompaniesCompletedEventHandler DeleteCompaniesCompleted;
        
        /// <remarks/>
        public event SaveRelationsCompletedEventHandler SaveRelationsCompleted;
        
        /// <remarks/>
        public event DeleteMapsCompletedEventHandler DeleteMapsCompleted;
        
        /// <remarks/>
        public event SaveMapsCompletedEventHandler SaveMapsCompleted;
        
        /// <remarks/>
        public event GetCompaniesCompletedEventHandler GetCompaniesCompleted;
        
        /// <remarks/>
        public event GetCategoriesCompletedEventHandler GetCategoriesCompleted;
        
        /// <remarks/>
        public event GetCustomerCategoriesCompletedEventHandler GetCustomerCategoriesCompleted;
        
        /// <remarks/>
        public event GetIndustriesCompletedEventHandler GetIndustriesCompleted;
        
        /// <remarks/>
        public event SaveCustomerCategoriesCompletedEventHandler SaveCustomerCategoriesCompleted;
        
        /// <remarks/>
        public event DeleteCustomerCategoriesCompletedEventHandler DeleteCustomerCategoriesCompleted;
        
        /// <remarks/>
        public event GetCustomerCategoryTreeCompletedEventHandler GetCustomerCategoryTreeCompleted;
        
        /// <remarks/>
        public event SaveCompaniesCompletedEventHandler SaveCompaniesCompleted;
        
        /// <remarks/>
        public event GetStatusesCompletedEventHandler GetStatusesCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://24sevenOffice.com/webservices/DeleteRelations", RequestNamespace="http://24sevenOffice.com/webservices", ResponseNamespace="http://24sevenOffice.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Relation[] DeleteRelations(Relation[] relations) {
            object[] results = this.Invoke("DeleteRelations", new object[] {
                        relations});
            return ((Relation[])(results[0]));
        }
        
        /// <remarks/>
        public void DeleteRelationsAsync(Relation[] relations) {
            this.DeleteRelationsAsync(relations, null);
        }
        
        /// <remarks/>
        public void DeleteRelationsAsync(Relation[] relations, object userState) {
            if ((this.DeleteRelationsOperationCompleted == null)) {
                this.DeleteRelationsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteRelationsOperationCompleted);
            }
            this.InvokeAsync("DeleteRelations", new object[] {
                        relations}, this.DeleteRelationsOperationCompleted, userState);
        }
        
        private void OnDeleteRelationsOperationCompleted(object arg) {
            if ((this.DeleteRelationsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteRelationsCompleted(this, new DeleteRelationsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://24sevenOffice.com/webservices/DeleteCompanies", RequestNamespace="http://24sevenOffice.com/webservices", ResponseNamespace="http://24sevenOffice.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Company[] DeleteCompanies(Company[] companies) {
            object[] results = this.Invoke("DeleteCompanies", new object[] {
                        companies});
            return ((Company[])(results[0]));
        }
        
        /// <remarks/>
        public void DeleteCompaniesAsync(Company[] companies) {
            this.DeleteCompaniesAsync(companies, null);
        }
        
        /// <remarks/>
        public void DeleteCompaniesAsync(Company[] companies, object userState) {
            if ((this.DeleteCompaniesOperationCompleted == null)) {
                this.DeleteCompaniesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteCompaniesOperationCompleted);
            }
            this.InvokeAsync("DeleteCompanies", new object[] {
                        companies}, this.DeleteCompaniesOperationCompleted, userState);
        }
        
        private void OnDeleteCompaniesOperationCompleted(object arg) {
            if ((this.DeleteCompaniesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteCompaniesCompleted(this, new DeleteCompaniesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://24sevenOffice.com/webservices/SaveRelations", RequestNamespace="http://24sevenOffice.com/webservices", ResponseNamespace="http://24sevenOffice.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Relation[] SaveRelations(Relation[] relations) {
            object[] results = this.Invoke("SaveRelations", new object[] {
                        relations});
            return ((Relation[])(results[0]));
        }
        
        /// <remarks/>
        public void SaveRelationsAsync(Relation[] relations) {
            this.SaveRelationsAsync(relations, null);
        }
        
        /// <remarks/>
        public void SaveRelationsAsync(Relation[] relations, object userState) {
            if ((this.SaveRelationsOperationCompleted == null)) {
                this.SaveRelationsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveRelationsOperationCompleted);
            }
            this.InvokeAsync("SaveRelations", new object[] {
                        relations}, this.SaveRelationsOperationCompleted, userState);
        }
        
        private void OnSaveRelationsOperationCompleted(object arg) {
            if ((this.SaveRelationsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveRelationsCompleted(this, new SaveRelationsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://24sevenOffice.com/webservices/DeleteMaps", RequestNamespace="http://24sevenOffice.com/webservices", ResponseNamespace="http://24sevenOffice.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CompanyMap[] DeleteMaps(CompanyMap[] maps) {
            object[] results = this.Invoke("DeleteMaps", new object[] {
                        maps});
            return ((CompanyMap[])(results[0]));
        }
        
        /// <remarks/>
        public void DeleteMapsAsync(CompanyMap[] maps) {
            this.DeleteMapsAsync(maps, null);
        }
        
        /// <remarks/>
        public void DeleteMapsAsync(CompanyMap[] maps, object userState) {
            if ((this.DeleteMapsOperationCompleted == null)) {
                this.DeleteMapsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteMapsOperationCompleted);
            }
            this.InvokeAsync("DeleteMaps", new object[] {
                        maps}, this.DeleteMapsOperationCompleted, userState);
        }
        
        private void OnDeleteMapsOperationCompleted(object arg) {
            if ((this.DeleteMapsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteMapsCompleted(this, new DeleteMapsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://24sevenOffice.com/webservices/SaveMaps", RequestNamespace="http://24sevenOffice.com/webservices", ResponseNamespace="http://24sevenOffice.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CompanyMap[] SaveMaps(CompanyMap[] maps) {
            object[] results = this.Invoke("SaveMaps", new object[] {
                        maps});
            return ((CompanyMap[])(results[0]));
        }
        
        /// <remarks/>
        public void SaveMapsAsync(CompanyMap[] maps) {
            this.SaveMapsAsync(maps, null);
        }
        
        /// <remarks/>
        public void SaveMapsAsync(CompanyMap[] maps, object userState) {
            if ((this.SaveMapsOperationCompleted == null)) {
                this.SaveMapsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveMapsOperationCompleted);
            }
            this.InvokeAsync("SaveMaps", new object[] {
                        maps}, this.SaveMapsOperationCompleted, userState);
        }
        
        private void OnSaveMapsOperationCompleted(object arg) {
            if ((this.SaveMapsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveMapsCompleted(this, new SaveMapsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://24sevenOffice.com/webservices/GetCompanies", RequestNamespace="http://24sevenOffice.com/webservices", ResponseNamespace="http://24sevenOffice.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Company[] GetCompanies(CompanySearchParameters searchParams, string[] returnProperties) {
            object[] results = this.Invoke("GetCompanies", new object[] {
                        searchParams,
                        returnProperties});
            return ((Company[])(results[0]));
        }
        
        /// <remarks/>
        public void GetCompaniesAsync(CompanySearchParameters searchParams, string[] returnProperties) {
            this.GetCompaniesAsync(searchParams, returnProperties, null);
        }
        
        /// <remarks/>
        public void GetCompaniesAsync(CompanySearchParameters searchParams, string[] returnProperties, object userState) {
            if ((this.GetCompaniesOperationCompleted == null)) {
                this.GetCompaniesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCompaniesOperationCompleted);
            }
            this.InvokeAsync("GetCompanies", new object[] {
                        searchParams,
                        returnProperties}, this.GetCompaniesOperationCompleted, userState);
        }
        
        private void OnGetCompaniesOperationCompleted(object arg) {
            if ((this.GetCompaniesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCompaniesCompleted(this, new GetCompaniesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://24sevenOffice.com/webservices/GetCategories", RequestNamespace="http://24sevenOffice.com/webservices", ResponseNamespace="http://24sevenOffice.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Category[] GetCategories() {
            object[] results = this.Invoke("GetCategories", new object[0]);
            return ((Category[])(results[0]));
        }
        
        /// <remarks/>
        public void GetCategoriesAsync() {
            this.GetCategoriesAsync(null);
        }
        
        /// <remarks/>
        public void GetCategoriesAsync(object userState) {
            if ((this.GetCategoriesOperationCompleted == null)) {
                this.GetCategoriesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCategoriesOperationCompleted);
            }
            this.InvokeAsync("GetCategories", new object[0], this.GetCategoriesOperationCompleted, userState);
        }
        
        private void OnGetCategoriesOperationCompleted(object arg) {
            if ((this.GetCategoriesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCategoriesCompleted(this, new GetCategoriesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://24sevenOffice.com/webservices/GetCustomerCategories", RequestNamespace="http://24sevenOffice.com/webservices", ResponseNamespace="http://24sevenOffice.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int[] GetCustomerCategories(int customerId) {
            object[] results = this.Invoke("GetCustomerCategories", new object[] {
                        customerId});
            return ((int[])(results[0]));
        }
        
        /// <remarks/>
        public void GetCustomerCategoriesAsync(int customerId) {
            this.GetCustomerCategoriesAsync(customerId, null);
        }
        
        /// <remarks/>
        public void GetCustomerCategoriesAsync(int customerId, object userState) {
            if ((this.GetCustomerCategoriesOperationCompleted == null)) {
                this.GetCustomerCategoriesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCustomerCategoriesOperationCompleted);
            }
            this.InvokeAsync("GetCustomerCategories", new object[] {
                        customerId}, this.GetCustomerCategoriesOperationCompleted, userState);
        }
        
        private void OnGetCustomerCategoriesOperationCompleted(object arg) {
            if ((this.GetCustomerCategoriesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCustomerCategoriesCompleted(this, new GetCustomerCategoriesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://24sevenOffice.com/webservices/GetIndustries", RequestNamespace="http://24sevenOffice.com/webservices", ResponseNamespace="http://24sevenOffice.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public KeyValuePair[] GetIndustries() {
            object[] results = this.Invoke("GetIndustries", new object[0]);
            return ((KeyValuePair[])(results[0]));
        }
        
        /// <remarks/>
        public void GetIndustriesAsync() {
            this.GetIndustriesAsync(null);
        }
        
        /// <remarks/>
        public void GetIndustriesAsync(object userState) {
            if ((this.GetIndustriesOperationCompleted == null)) {
                this.GetIndustriesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetIndustriesOperationCompleted);
            }
            this.InvokeAsync("GetIndustries", new object[0], this.GetIndustriesOperationCompleted, userState);
        }
        
        private void OnGetIndustriesOperationCompleted(object arg) {
            if ((this.GetIndustriesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetIndustriesCompleted(this, new GetIndustriesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://24sevenOffice.com/webservices/SaveCustomerCategories", RequestNamespace="http://24sevenOffice.com/webservices", ResponseNamespace="http://24sevenOffice.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public APIException[] SaveCustomerCategories([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] KeyValuePair[] customerCategories) {
            object[] results = this.Invoke("SaveCustomerCategories", new object[] {
                        customerCategories});
            return ((APIException[])(results[0]));
        }
        
        /// <remarks/>
        public void SaveCustomerCategoriesAsync(KeyValuePair[] customerCategories) {
            this.SaveCustomerCategoriesAsync(customerCategories, null);
        }
        
        /// <remarks/>
        public void SaveCustomerCategoriesAsync(KeyValuePair[] customerCategories, object userState) {
            if ((this.SaveCustomerCategoriesOperationCompleted == null)) {
                this.SaveCustomerCategoriesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveCustomerCategoriesOperationCompleted);
            }
            this.InvokeAsync("SaveCustomerCategories", new object[] {
                        customerCategories}, this.SaveCustomerCategoriesOperationCompleted, userState);
        }
        
        private void OnSaveCustomerCategoriesOperationCompleted(object arg) {
            if ((this.SaveCustomerCategoriesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveCustomerCategoriesCompleted(this, new SaveCustomerCategoriesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://24sevenOffice.com/webservices/DeleteCustomerCategories", RequestNamespace="http://24sevenOffice.com/webservices", ResponseNamespace="http://24sevenOffice.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public APIException[] DeleteCustomerCategories([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] KeyValuePair[] customerCategories) {
            object[] results = this.Invoke("DeleteCustomerCategories", new object[] {
                        customerCategories});
            return ((APIException[])(results[0]));
        }
        
        /// <remarks/>
        public void DeleteCustomerCategoriesAsync(KeyValuePair[] customerCategories) {
            this.DeleteCustomerCategoriesAsync(customerCategories, null);
        }
        
        /// <remarks/>
        public void DeleteCustomerCategoriesAsync(KeyValuePair[] customerCategories, object userState) {
            if ((this.DeleteCustomerCategoriesOperationCompleted == null)) {
                this.DeleteCustomerCategoriesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteCustomerCategoriesOperationCompleted);
            }
            this.InvokeAsync("DeleteCustomerCategories", new object[] {
                        customerCategories}, this.DeleteCustomerCategoriesOperationCompleted, userState);
        }
        
        private void OnDeleteCustomerCategoriesOperationCompleted(object arg) {
            if ((this.DeleteCustomerCategoriesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteCustomerCategoriesCompleted(this, new DeleteCustomerCategoriesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://24sevenOffice.com/webservices/GetCustomerCategoryTree", RequestNamespace="http://24sevenOffice.com/webservices", ResponseNamespace="http://24sevenOffice.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public KeyValuePair[] GetCustomerCategoryTree() {
            object[] results = this.Invoke("GetCustomerCategoryTree", new object[0]);
            return ((KeyValuePair[])(results[0]));
        }
        
        /// <remarks/>
        public void GetCustomerCategoryTreeAsync() {
            this.GetCustomerCategoryTreeAsync(null);
        }
        
        /// <remarks/>
        public void GetCustomerCategoryTreeAsync(object userState) {
            if ((this.GetCustomerCategoryTreeOperationCompleted == null)) {
                this.GetCustomerCategoryTreeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCustomerCategoryTreeOperationCompleted);
            }
            this.InvokeAsync("GetCustomerCategoryTree", new object[0], this.GetCustomerCategoryTreeOperationCompleted, userState);
        }
        
        private void OnGetCustomerCategoryTreeOperationCompleted(object arg) {
            if ((this.GetCustomerCategoryTreeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCustomerCategoryTreeCompleted(this, new GetCustomerCategoryTreeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://24sevenOffice.com/webservices/SaveCompanies", RequestNamespace="http://24sevenOffice.com/webservices", ResponseNamespace="http://24sevenOffice.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Company[] SaveCompanies(Company[] companies) {
            object[] results = this.Invoke("SaveCompanies", new object[] {
                        companies});
            return ((Company[])(results[0]));
        }
        
        /// <remarks/>
        public void SaveCompaniesAsync(Company[] companies) {
            this.SaveCompaniesAsync(companies, null);
        }
        
        /// <remarks/>
        public void SaveCompaniesAsync(Company[] companies, object userState) {
            if ((this.SaveCompaniesOperationCompleted == null)) {
                this.SaveCompaniesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveCompaniesOperationCompleted);
            }
            this.InvokeAsync("SaveCompanies", new object[] {
                        companies}, this.SaveCompaniesOperationCompleted, userState);
        }
        
        private void OnSaveCompaniesOperationCompleted(object arg) {
            if ((this.SaveCompaniesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveCompaniesCompleted(this, new SaveCompaniesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://24sevenOffice.com/webservices/GetStatuses", RequestNamespace="http://24sevenOffice.com/webservices", ResponseNamespace="http://24sevenOffice.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public KeyValuePair[] GetStatuses() {
            object[] results = this.Invoke("GetStatuses", new object[0]);
            return ((KeyValuePair[])(results[0]));
        }
        
        /// <remarks/>
        public void GetStatusesAsync() {
            this.GetStatusesAsync(null);
        }
        
        /// <remarks/>
        public void GetStatusesAsync(object userState) {
            if ((this.GetStatusesOperationCompleted == null)) {
                this.GetStatusesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetStatusesOperationCompleted);
            }
            this.InvokeAsync("GetStatuses", new object[0], this.GetStatusesOperationCompleted, userState);
        }
        
        private void OnGetStatusesOperationCompleted(object arg) {
            if ((this.GetStatusesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetStatusesCompleted(this, new GetStatusesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public partial class Relation {
        
        private int contactIdField;
        
        private int companyIdField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string roleField;
        
        private int roleIdField;
        
        private PhoneNumbers phoneNumbersField;
        
        private EmailAddresses emailAddressesField;
        
        private string faxField;
        
        public Relation() {
            this.contactIdField = -2147483648;
            this.companyIdField = -2147483648;
            this.firstNameField = "";
            this.lastNameField = "";
            this.roleField = "";
            this.roleIdField = -2147483648;
            this.faxField = "";
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int ContactId {
            get {
                return this.contactIdField;
            }
            set {
                this.contactIdField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int CompanyId {
            get {
                return this.companyIdField;
            }
            set {
                this.companyIdField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("")]
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("")]
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("")]
        public string Role {
            get {
                return this.roleField;
            }
            set {
                this.roleField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int RoleId {
            get {
                return this.roleIdField;
            }
            set {
                this.roleIdField = value;
            }
        }
        
        /// <remarks/>
        public PhoneNumbers PhoneNumbers {
            get {
                return this.phoneNumbersField;
            }
            set {
                this.phoneNumbersField = value;
            }
        }
        
        /// <remarks/>
        public EmailAddresses EmailAddresses {
            get {
                return this.emailAddressesField;
            }
            set {
                this.emailAddressesField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("")]
        public string Fax {
            get {
                return this.faxField;
            }
            set {
                this.faxField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public partial class PhoneNumbers {
        
        private PhoneNumber homeField;
        
        private PhoneNumber faxField;
        
        private PhoneNumber mobileField;
        
        private PhoneNumber primaryField;
        
        private PhoneNumber workField;
        
        /// <remarks/>
        public PhoneNumber Home {
            get {
                return this.homeField;
            }
            set {
                this.homeField = value;
            }
        }
        
        /// <remarks/>
        public PhoneNumber Fax {
            get {
                return this.faxField;
            }
            set {
                this.faxField = value;
            }
        }
        
        /// <remarks/>
        public PhoneNumber Mobile {
            get {
                return this.mobileField;
            }
            set {
                this.mobileField = value;
            }
        }
        
        /// <remarks/>
        public PhoneNumber Primary {
            get {
                return this.primaryField;
            }
            set {
                this.primaryField = value;
            }
        }
        
        /// <remarks/>
        public PhoneNumber Work {
            get {
                return this.workField;
            }
            set {
                this.workField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public partial class PhoneNumber {
        
        private string descriptionField;
        
        private string valueField;
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public partial class KeyValuePair {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public partial class Category {
        
        private int idField;
        
        private string nameField;
        
        private bool showContactField;
        
        private bool showCompanyField;
        
        public Category() {
            this.idField = -2147483648;
            this.nameField = "";
            this.showContactField = false;
            this.showCompanyField = false;
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("")]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool ShowContact {
            get {
                return this.showContactField;
            }
            set {
                this.showContactField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool ShowCompany {
            get {
                return this.showCompanyField;
            }
            set {
                this.showCompanyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public partial class CompanySearchParameters {
        
        private string externalIdField;
        
        private int companyIdField;
        
        private string companyNameField;
        
        private System.DateTime changedAfterField;
        
        private string companyEmailField;
        
        public CompanySearchParameters() {
            this.companyIdField = -2147483648;
            this.companyNameField = "";
            this.changedAfterField = new System.DateTime(0);
            this.companyEmailField = "";
        }
        
        /// <remarks/>
        public string ExternalId {
            get {
                return this.externalIdField;
            }
            set {
                this.externalIdField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int CompanyId {
            get {
                return this.companyIdField;
            }
            set {
                this.companyIdField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("")]
        public string CompanyName {
            get {
                return this.companyNameField;
            }
            set {
                this.companyNameField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(System.DateTime), "0001-01-01T00:00:00")]
        public System.DateTime ChangedAfter {
            get {
                return this.changedAfterField;
            }
            set {
                this.changedAfterField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("")]
        public string CompanyEmail {
            get {
                return this.companyEmailField;
            }
            set {
                this.companyEmailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public partial class CompanyMap {
        
        private int mapTypeField;
        
        private string externalIdField;
        
        private int companyIdField;
        
        /// <remarks/>
        public int MapType {
            get {
                return this.mapTypeField;
            }
            set {
                this.mapTypeField = value;
            }
        }
        
        /// <remarks/>
        public string ExternalId {
            get {
                return this.externalIdField;
            }
            set {
                this.externalIdField = value;
            }
        }
        
        /// <remarks/>
        public int CompanyId {
            get {
                return this.companyIdField;
            }
            set {
                this.companyIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public partial class Address {
        
        private string streetField;
        
        private string stateField;
        
        private string postalCodeField;
        
        private string postalAreaField;
        
        private string nameField;
        
        private string cityField;
        
        private string countryField;
        
        /// <remarks/>
        public string Street {
            get {
                return this.streetField;
            }
            set {
                this.streetField = value;
            }
        }
        
        /// <remarks/>
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public string PostalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
            }
        }
        
        /// <remarks/>
        public string PostalArea {
            get {
                return this.postalAreaField;
            }
            set {
                this.postalAreaField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public partial class Addresses {
        
        private Address postField;
        
        private Address deliveryField;
        
        private Address visitField;
        
        private Address invoiceField;
        
        /// <remarks/>
        public Address Post {
            get {
                return this.postField;
            }
            set {
                this.postField = value;
            }
        }
        
        /// <remarks/>
        public Address Delivery {
            get {
                return this.deliveryField;
            }
            set {
                this.deliveryField = value;
            }
        }
        
        /// <remarks/>
        public Address Visit {
            get {
                return this.visitField;
            }
            set {
                this.visitField = value;
            }
        }
        
        /// <remarks/>
        public Address Invoice {
            get {
                return this.invoiceField;
            }
            set {
                this.invoiceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public partial class APIException {
        
        private string typeField;
        
        private string messageField;
        
        private string stackTraceField;
        
        /// <remarks/>
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public string StackTrace {
            get {
                return this.stackTraceField;
            }
            set {
                this.stackTraceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public partial class Company {
        
        private APIException aPIExceptionField;
        
        private int idField;
        
        private string externalIdField;
        
        private string organizationNumberField;
        
        private string nameField;
        
        private string firstNameField;
        
        private string nickNameField;
        
        private Addresses addressesField;
        
        private PhoneNumbers phoneNumbersField;
        
        private EmailAddresses emailAddressesField;
        
        private string urlField;
        
        private string countryField;
        
        private string noteField;
        
        private string invoiceLanguageField;
        
        private CompanyType typeField;
        
        private string usernameField;
        
        private string passwordField;
        
        private System.DateTime incorporationDateField;
        
        private System.DateTime dateCreatedField;
        
        private int statusField;
        
        private int priceListField;
        
        private int ownerField;
        
        private string bankAccountNoField;
        
        private int termsOfDeliveryIdField;
        
        private short accountDebitField;
        
        private short accountCreditField;
        
        private decimal discountField;
        
        private int typeGroupField;
        
        private decimal shareCapitalField;
        
        private int numberOfEmployeesField;
        
        private decimal turnoverField;
        
        private decimal profitField;
        
        private int industryIdField;
        
        private int memberNoField;
        
        private System.DateTime dateChangedField;
        
        private bool blockInvoiceField;
        
        private Relation[] relationsField;
        
        private CompanyMap[] mapsField;
        
        private DistributionMethod distributionMethodField;
        
        private CurrencyType currencyIdField;
        
        private short paymentTimeField;
        
        private string glnNumberField;
        
        private System.Nullable<bool> factoringField;
        
        private bool factoringFieldSpecified;
        
        private short ledgerCustomerAccountField;
        
        private short ledgerSupplierAccountField;
        
        private string vatNumberField;
        
        private System.Nullable<bool> privateField;
        
        private bool privateFieldSpecified;
        
        public Company() {
            this.idField = -2147483648;
            this.externalIdField = "";
            this.organizationNumberField = "";
            this.nameField = "";
            this.firstNameField = "";
            this.nickNameField = "";
            this.urlField = "";
            this.countryField = "EN";
            this.noteField = "";
            this.invoiceLanguageField = "";
            this.typeField = CompanyType.None;
            this.usernameField = "";
            this.passwordField = "";
            this.incorporationDateField = new System.DateTime(0);
            this.dateCreatedField = new System.DateTime(0);
            this.statusField = -2147483648;
            this.priceListField = -2147483648;
            this.ownerField = -2147483648;
            this.bankAccountNoField = "";
            this.termsOfDeliveryIdField = -2147483648;
            this.accountDebitField = ((short)(0));
            this.accountCreditField = ((short)(0));
            this.discountField = ((decimal)(0.0m));
            this.typeGroupField = -2147483648;
            this.shareCapitalField = ((decimal)(-79228162514264337593543950335m));
            this.numberOfEmployeesField = -2147483648;
            this.turnoverField = ((decimal)(-79228162514264337593543950335m));
            this.profitField = ((decimal)(-79228162514264337593543950335m));
            this.industryIdField = -2147483648;
            this.memberNoField = -2147483648;
            this.dateChangedField = new System.DateTime(0);
            this.blockInvoiceField = false;
            this.distributionMethodField = DistributionMethod.Unchanged;
            this.currencyIdField = CurrencyType.LOCAL;
            this.paymentTimeField = ((short)(-32768));
            this.glnNumberField = "";
            this.ledgerCustomerAccountField = ((short)(-32768));
            this.ledgerSupplierAccountField = ((short)(-32768));
            this.vatNumberField = "";
        }
        
        /// <remarks/>
        public APIException APIException {
            get {
                return this.aPIExceptionField;
            }
            set {
                this.aPIExceptionField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("")]
        public string ExternalId {
            get {
                return this.externalIdField;
            }
            set {
                this.externalIdField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("")]
        public string OrganizationNumber {
            get {
                return this.organizationNumberField;
            }
            set {
                this.organizationNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("")]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("")]
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("")]
        public string NickName {
            get {
                return this.nickNameField;
            }
            set {
                this.nickNameField = value;
            }
        }
        
        /// <remarks/>
        public Addresses Addresses {
            get {
                return this.addressesField;
            }
            set {
                this.addressesField = value;
            }
        }
        
        /// <remarks/>
        public PhoneNumbers PhoneNumbers {
            get {
                return this.phoneNumbersField;
            }
            set {
                this.phoneNumbersField = value;
            }
        }
        
        /// <remarks/>
        public EmailAddresses EmailAddresses {
            get {
                return this.emailAddressesField;
            }
            set {
                this.emailAddressesField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("")]
        public string Url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("EN")]
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("")]
        public string Note {
            get {
                return this.noteField;
            }
            set {
                this.noteField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("")]
        public string InvoiceLanguage {
            get {
                return this.invoiceLanguageField;
            }
            set {
                this.invoiceLanguageField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(CompanyType.None)]
        public CompanyType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("")]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("")]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(System.DateTime), "0001-01-01T00:00:00")]
        public System.DateTime IncorporationDate {
            get {
                return this.incorporationDateField;
            }
            set {
                this.incorporationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(System.DateTime), "0001-01-01T00:00:00")]
        public System.DateTime DateCreated {
            get {
                return this.dateCreatedField;
            }
            set {
                this.dateCreatedField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int PriceList {
            get {
                return this.priceListField;
            }
            set {
                this.priceListField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int Owner {
            get {
                return this.ownerField;
            }
            set {
                this.ownerField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("")]
        public string BankAccountNo {
            get {
                return this.bankAccountNoField;
            }
            set {
                this.bankAccountNoField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int TermsOfDeliveryId {
            get {
                return this.termsOfDeliveryIdField;
            }
            set {
                this.termsOfDeliveryIdField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(short), "0")]
        public short AccountDebit {
            get {
                return this.accountDebitField;
            }
            set {
                this.accountDebitField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(short), "0")]
        public short AccountCredit {
            get {
                return this.accountCreditField;
            }
            set {
                this.accountCreditField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "0.0")]
        public decimal Discount {
            get {
                return this.discountField;
            }
            set {
                this.discountField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int TypeGroup {
            get {
                return this.typeGroupField;
            }
            set {
                this.typeGroupField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "-79228162514264337593543950335")]
        public decimal ShareCapital {
            get {
                return this.shareCapitalField;
            }
            set {
                this.shareCapitalField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int NumberOfEmployees {
            get {
                return this.numberOfEmployeesField;
            }
            set {
                this.numberOfEmployeesField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "-79228162514264337593543950335")]
        public decimal Turnover {
            get {
                return this.turnoverField;
            }
            set {
                this.turnoverField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "-79228162514264337593543950335")]
        public decimal Profit {
            get {
                return this.profitField;
            }
            set {
                this.profitField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int IndustryId {
            get {
                return this.industryIdField;
            }
            set {
                this.industryIdField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int MemberNo {
            get {
                return this.memberNoField;
            }
            set {
                this.memberNoField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(System.DateTime), "0001-01-01T00:00:00")]
        public System.DateTime DateChanged {
            get {
                return this.dateChangedField;
            }
            set {
                this.dateChangedField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool BlockInvoice {
            get {
                return this.blockInvoiceField;
            }
            set {
                this.blockInvoiceField = value;
            }
        }
        
        /// <remarks/>
        public Relation[] Relations {
            get {
                return this.relationsField;
            }
            set {
                this.relationsField = value;
            }
        }
        
        /// <remarks/>
        public CompanyMap[] Maps {
            get {
                return this.mapsField;
            }
            set {
                this.mapsField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(DistributionMethod.Unchanged)]
        public DistributionMethod DistributionMethod {
            get {
                return this.distributionMethodField;
            }
            set {
                this.distributionMethodField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(CurrencyType.LOCAL)]
        public CurrencyType CurrencyId {
            get {
                return this.currencyIdField;
            }
            set {
                this.currencyIdField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(short), "-32768")]
        public short PaymentTime {
            get {
                return this.paymentTimeField;
            }
            set {
                this.paymentTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("")]
        public string GlnNumber {
            get {
                return this.glnNumberField;
            }
            set {
                this.glnNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> Factoring {
            get {
                return this.factoringField;
            }
            set {
                this.factoringField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FactoringSpecified {
            get {
                return this.factoringFieldSpecified;
            }
            set {
                this.factoringFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(short), "-32768")]
        public short LedgerCustomerAccount {
            get {
                return this.ledgerCustomerAccountField;
            }
            set {
                this.ledgerCustomerAccountField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(short), "-32768")]
        public short LedgerSupplierAccount {
            get {
                return this.ledgerSupplierAccountField;
            }
            set {
                this.ledgerSupplierAccountField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("")]
        public string VatNumber {
            get {
                return this.vatNumberField;
            }
            set {
                this.vatNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> Private {
            get {
                return this.privateField;
            }
            set {
                this.privateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PrivateSpecified {
            get {
                return this.privateFieldSpecified;
            }
            set {
                this.privateFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public partial class EmailAddresses {
        
        private EmailAddress homeField;
        
        private EmailAddress invoiceField;
        
        private EmailAddress primaryField;
        
        private EmailAddress workField;
        
        private EmailAddress alternativeField;
        
        /// <remarks/>
        public EmailAddress Home {
            get {
                return this.homeField;
            }
            set {
                this.homeField = value;
            }
        }
        
        /// <remarks/>
        public EmailAddress Invoice {
            get {
                return this.invoiceField;
            }
            set {
                this.invoiceField = value;
            }
        }
        
        /// <remarks/>
        public EmailAddress Primary {
            get {
                return this.primaryField;
            }
            set {
                this.primaryField = value;
            }
        }
        
        /// <remarks/>
        public EmailAddress Work {
            get {
                return this.workField;
            }
            set {
                this.workField = value;
            }
        }
        
        /// <remarks/>
        public EmailAddress Alternative {
            get {
                return this.alternativeField;
            }
            set {
                this.alternativeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public partial class EmailAddress {
        
        private string descriptionField;
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public enum CompanyType {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        Lead,
        
        /// <remarks/>
        Consumer,
        
        /// <remarks/>
        Business,
        
        /// <remarks/>
        Supplier,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public enum DistributionMethod {
        
        /// <remarks/>
        Unchanged,
        
        /// <remarks/>
        Print,
        
        /// <remarks/>
        EMail,
        
        /// <remarks/>
        ElectronicInvoice,
        
        /// <remarks/>
        Default,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public enum CurrencyType {
        
        /// <remarks/>
        LOCAL,
        
        /// <remarks/>
        AED,
        
        /// <remarks/>
        AFN,
        
        /// <remarks/>
        ALL,
        
        /// <remarks/>
        AMD,
        
        /// <remarks/>
        ANG,
        
        /// <remarks/>
        AOA,
        
        /// <remarks/>
        ARS,
        
        /// <remarks/>
        AUD,
        
        /// <remarks/>
        AWG,
        
        /// <remarks/>
        AZN,
        
        /// <remarks/>
        BAM,
        
        /// <remarks/>
        BBD,
        
        /// <remarks/>
        BDT,
        
        /// <remarks/>
        BGN,
        
        /// <remarks/>
        BHD,
        
        /// <remarks/>
        BIF,
        
        /// <remarks/>
        BMD,
        
        /// <remarks/>
        BND,
        
        /// <remarks/>
        BOB,
        
        /// <remarks/>
        BOV,
        
        /// <remarks/>
        BRL,
        
        /// <remarks/>
        BSD,
        
        /// <remarks/>
        BTN,
        
        /// <remarks/>
        BWP,
        
        /// <remarks/>
        BYN,
        
        /// <remarks/>
        BYR,
        
        /// <remarks/>
        BZD,
        
        /// <remarks/>
        CAD,
        
        /// <remarks/>
        CDF,
        
        /// <remarks/>
        CHE,
        
        /// <remarks/>
        CHF,
        
        /// <remarks/>
        CHW,
        
        /// <remarks/>
        CLF,
        
        /// <remarks/>
        CLP,
        
        /// <remarks/>
        CNY,
        
        /// <remarks/>
        COP,
        
        /// <remarks/>
        COU,
        
        /// <remarks/>
        CRC,
        
        /// <remarks/>
        CUC,
        
        /// <remarks/>
        CUP,
        
        /// <remarks/>
        CVE,
        
        /// <remarks/>
        CZK,
        
        /// <remarks/>
        DJF,
        
        /// <remarks/>
        DKK,
        
        /// <remarks/>
        DOP,
        
        /// <remarks/>
        DZD,
        
        /// <remarks/>
        EEK,
        
        /// <remarks/>
        EGP,
        
        /// <remarks/>
        ERN,
        
        /// <remarks/>
        ETB,
        
        /// <remarks/>
        EUR,
        
        /// <remarks/>
        FJD,
        
        /// <remarks/>
        FKP,
        
        /// <remarks/>
        GBP,
        
        /// <remarks/>
        GEL,
        
        /// <remarks/>
        GHS,
        
        /// <remarks/>
        GIP,
        
        /// <remarks/>
        GMD,
        
        /// <remarks/>
        GNF,
        
        /// <remarks/>
        GTQ,
        
        /// <remarks/>
        GYD,
        
        /// <remarks/>
        HKD,
        
        /// <remarks/>
        HNL,
        
        /// <remarks/>
        HRK,
        
        /// <remarks/>
        HTG,
        
        /// <remarks/>
        HUF,
        
        /// <remarks/>
        IDR,
        
        /// <remarks/>
        ILS,
        
        /// <remarks/>
        INR,
        
        /// <remarks/>
        IQD,
        
        /// <remarks/>
        IRR,
        
        /// <remarks/>
        ISK,
        
        /// <remarks/>
        JMD,
        
        /// <remarks/>
        JOD,
        
        /// <remarks/>
        JPY,
        
        /// <remarks/>
        KES,
        
        /// <remarks/>
        KGS,
        
        /// <remarks/>
        KHR,
        
        /// <remarks/>
        KMF,
        
        /// <remarks/>
        KPW,
        
        /// <remarks/>
        KRW,
        
        /// <remarks/>
        KWD,
        
        /// <remarks/>
        KYD,
        
        /// <remarks/>
        KZT,
        
        /// <remarks/>
        LAK,
        
        /// <remarks/>
        LBP,
        
        /// <remarks/>
        LKR,
        
        /// <remarks/>
        LRD,
        
        /// <remarks/>
        LSL,
        
        /// <remarks/>
        LTL,
        
        /// <remarks/>
        LVL,
        
        /// <remarks/>
        LYD,
        
        /// <remarks/>
        MAD,
        
        /// <remarks/>
        MDL,
        
        /// <remarks/>
        MGA,
        
        /// <remarks/>
        MKD,
        
        /// <remarks/>
        MMK,
        
        /// <remarks/>
        MNT,
        
        /// <remarks/>
        MOP,
        
        /// <remarks/>
        MRO,
        
        /// <remarks/>
        MTL,
        
        /// <remarks/>
        MUR,
        
        /// <remarks/>
        MVR,
        
        /// <remarks/>
        MWK,
        
        /// <remarks/>
        MXN,
        
        /// <remarks/>
        MXV,
        
        /// <remarks/>
        MYR,
        
        /// <remarks/>
        MZN,
        
        /// <remarks/>
        NAD,
        
        /// <remarks/>
        NGN,
        
        /// <remarks/>
        NIO,
        
        /// <remarks/>
        NOK,
        
        /// <remarks/>
        NPR,
        
        /// <remarks/>
        NZD,
        
        /// <remarks/>
        OMR,
        
        /// <remarks/>
        PAB,
        
        /// <remarks/>
        PEN,
        
        /// <remarks/>
        PGK,
        
        /// <remarks/>
        PHP,
        
        /// <remarks/>
        PKR,
        
        /// <remarks/>
        PLN,
        
        /// <remarks/>
        PYG,
        
        /// <remarks/>
        QAR,
        
        /// <remarks/>
        RON,
        
        /// <remarks/>
        RSD,
        
        /// <remarks/>
        RUB,
        
        /// <remarks/>
        RWF,
        
        /// <remarks/>
        SAR,
        
        /// <remarks/>
        SBD,
        
        /// <remarks/>
        SCR,
        
        /// <remarks/>
        SDG,
        
        /// <remarks/>
        SEK,
        
        /// <remarks/>
        SGD,
        
        /// <remarks/>
        SHP,
        
        /// <remarks/>
        SKK,
        
        /// <remarks/>
        SLL,
        
        /// <remarks/>
        SOS,
        
        /// <remarks/>
        SRD,
        
        /// <remarks/>
        STD,
        
        /// <remarks/>
        SYP,
        
        /// <remarks/>
        SZL,
        
        /// <remarks/>
        THB,
        
        /// <remarks/>
        TJS,
        
        /// <remarks/>
        TMT,
        
        /// <remarks/>
        TND,
        
        /// <remarks/>
        TOP,
        
        /// <remarks/>
        TRY,
        
        /// <remarks/>
        TTD,
        
        /// <remarks/>
        TWD,
        
        /// <remarks/>
        TZS,
        
        /// <remarks/>
        UAH,
        
        /// <remarks/>
        UGX,
        
        /// <remarks/>
        USD,
        
        /// <remarks/>
        UYU,
        
        /// <remarks/>
        UZS,
        
        /// <remarks/>
        VEF,
        
        /// <remarks/>
        VND,
        
        /// <remarks/>
        VUV,
        
        /// <remarks/>
        WST,
        
        /// <remarks/>
        XAF,
        
        /// <remarks/>
        XAG,
        
        /// <remarks/>
        XAU,
        
        /// <remarks/>
        XBA,
        
        /// <remarks/>
        XBB,
        
        /// <remarks/>
        XBC,
        
        /// <remarks/>
        XBD,
        
        /// <remarks/>
        XCD,
        
        /// <remarks/>
        XDR,
        
        /// <remarks/>
        XFU,
        
        /// <remarks/>
        XOF,
        
        /// <remarks/>
        XPD,
        
        /// <remarks/>
        XPF,
        
        /// <remarks/>
        XPT,
        
        /// <remarks/>
        XTS,
        
        /// <remarks/>
        XXX,
        
        /// <remarks/>
        YER,
        
        /// <remarks/>
        ZAR,
        
        /// <remarks/>
        ZMK,
        
        /// <remarks/>
        ZWL,
        
        /// <remarks/>
        ZWD,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void DeleteRelationsCompletedEventHandler(object sender, DeleteRelationsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteRelationsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteRelationsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Relation[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Relation[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void DeleteCompaniesCompletedEventHandler(object sender, DeleteCompaniesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteCompaniesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteCompaniesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Company[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Company[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void SaveRelationsCompletedEventHandler(object sender, SaveRelationsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveRelationsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveRelationsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Relation[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Relation[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void DeleteMapsCompletedEventHandler(object sender, DeleteMapsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteMapsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteMapsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CompanyMap[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CompanyMap[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void SaveMapsCompletedEventHandler(object sender, SaveMapsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveMapsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveMapsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CompanyMap[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CompanyMap[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetCompaniesCompletedEventHandler(object sender, GetCompaniesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCompaniesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCompaniesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Company[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Company[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetCategoriesCompletedEventHandler(object sender, GetCategoriesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCategoriesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCategoriesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Category[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Category[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetCustomerCategoriesCompletedEventHandler(object sender, GetCustomerCategoriesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCustomerCategoriesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCustomerCategoriesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetIndustriesCompletedEventHandler(object sender, GetIndustriesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetIndustriesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetIndustriesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public KeyValuePair[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((KeyValuePair[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void SaveCustomerCategoriesCompletedEventHandler(object sender, SaveCustomerCategoriesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveCustomerCategoriesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveCustomerCategoriesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public APIException[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((APIException[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void DeleteCustomerCategoriesCompletedEventHandler(object sender, DeleteCustomerCategoriesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteCustomerCategoriesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteCustomerCategoriesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public APIException[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((APIException[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetCustomerCategoryTreeCompletedEventHandler(object sender, GetCustomerCategoryTreeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCustomerCategoryTreeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCustomerCategoryTreeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public KeyValuePair[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((KeyValuePair[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void SaveCompaniesCompletedEventHandler(object sender, SaveCompaniesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveCompaniesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveCompaniesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Company[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Company[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetStatusesCompletedEventHandler(object sender, GetStatusesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetStatusesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetStatusesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public KeyValuePair[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((KeyValuePair[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591