//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace in24seven.autenticateRef {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AuthenticateSoap", Namespace="http://24sevenOffice.com/webservices")]
    public partial class Authenticate : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AuthenticateByTokenOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback HasSessionOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetIdentityOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetIdentitiesOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetIdentityOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetIdentityByIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetIdentitiesWithCredentialOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetIdentitiesWithCredentialByServiceOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Authenticate() {
            this.Url = global::in24seven.Properties.Settings.Default.in24seven_autenticateRef_Authenticate;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AuthenticateByTokenCompletedEventHandler AuthenticateByTokenCompleted;
        
        /// <remarks/>
        public event LoginCompletedEventHandler LoginCompleted;
        
        /// <remarks/>
        public event HasSessionCompletedEventHandler HasSessionCompleted;
        
        /// <remarks/>
        public event GetIdentityCompletedEventHandler GetIdentityCompleted;
        
        /// <remarks/>
        public event GetIdentitiesCompletedEventHandler GetIdentitiesCompleted;
        
        /// <remarks/>
        public event SetIdentityCompletedEventHandler SetIdentityCompleted;
        
        /// <remarks/>
        public event SetIdentityByIdCompletedEventHandler SetIdentityByIdCompleted;
        
        /// <remarks/>
        public event GetIdentitiesWithCredentialCompletedEventHandler GetIdentitiesWithCredentialCompleted;
        
        /// <remarks/>
        public event GetIdentitiesWithCredentialByServiceCompletedEventHandler GetIdentitiesWithCredentialByServiceCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://24sevenOffice.com/webservices/AuthenticateByToken", RequestNamespace="http://24sevenOffice.com/webservices", ResponseNamespace="http://24sevenOffice.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Passport AuthenticateByToken(Token token) {
            object[] results = this.Invoke("AuthenticateByToken", new object[] {
                        token});
            return ((Passport)(results[0]));
        }
        
        /// <remarks/>
        public void AuthenticateByTokenAsync(Token token) {
            this.AuthenticateByTokenAsync(token, null);
        }
        
        /// <remarks/>
        public void AuthenticateByTokenAsync(Token token, object userState) {
            if ((this.AuthenticateByTokenOperationCompleted == null)) {
                this.AuthenticateByTokenOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAuthenticateByTokenOperationCompleted);
            }
            this.InvokeAsync("AuthenticateByToken", new object[] {
                        token}, this.AuthenticateByTokenOperationCompleted, userState);
        }
        
        private void OnAuthenticateByTokenOperationCompleted(object arg) {
            if ((this.AuthenticateByTokenCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AuthenticateByTokenCompleted(this, new AuthenticateByTokenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://24sevenOffice.com/webservices/Login", RequestNamespace="http://24sevenOffice.com/webservices", ResponseNamespace="http://24sevenOffice.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Login(Credential credential) {
            object[] results = this.Invoke("Login", new object[] {
                        credential});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void LoginAsync(Credential credential) {
            this.LoginAsync(credential, null);
        }
        
        /// <remarks/>
        public void LoginAsync(Credential credential, object userState) {
            if ((this.LoginOperationCompleted == null)) {
                this.LoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginOperationCompleted);
            }
            this.InvokeAsync("Login", new object[] {
                        credential}, this.LoginOperationCompleted, userState);
        }
        
        private void OnLoginOperationCompleted(object arg) {
            if ((this.LoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginCompleted(this, new LoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://24sevenOffice.com/webservices/HasSession", RequestNamespace="http://24sevenOffice.com/webservices", ResponseNamespace="http://24sevenOffice.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool HasSession() {
            object[] results = this.Invoke("HasSession", new object[0]);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void HasSessionAsync() {
            this.HasSessionAsync(null);
        }
        
        /// <remarks/>
        public void HasSessionAsync(object userState) {
            if ((this.HasSessionOperationCompleted == null)) {
                this.HasSessionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHasSessionOperationCompleted);
            }
            this.InvokeAsync("HasSession", new object[0], this.HasSessionOperationCompleted, userState);
        }
        
        private void OnHasSessionOperationCompleted(object arg) {
            if ((this.HasSessionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HasSessionCompleted(this, new HasSessionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://24sevenOffice.com/webservices/GetIdentity", RequestNamespace="http://24sevenOffice.com/webservices", ResponseNamespace="http://24sevenOffice.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Identity GetIdentity() {
            object[] results = this.Invoke("GetIdentity", new object[0]);
            return ((Identity)(results[0]));
        }
        
        /// <remarks/>
        public void GetIdentityAsync() {
            this.GetIdentityAsync(null);
        }
        
        /// <remarks/>
        public void GetIdentityAsync(object userState) {
            if ((this.GetIdentityOperationCompleted == null)) {
                this.GetIdentityOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetIdentityOperationCompleted);
            }
            this.InvokeAsync("GetIdentity", new object[0], this.GetIdentityOperationCompleted, userState);
        }
        
        private void OnGetIdentityOperationCompleted(object arg) {
            if ((this.GetIdentityCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetIdentityCompleted(this, new GetIdentityCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://24sevenOffice.com/webservices/GetIdentities", RequestNamespace="http://24sevenOffice.com/webservices", ResponseNamespace="http://24sevenOffice.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Identity[] GetIdentities() {
            object[] results = this.Invoke("GetIdentities", new object[0]);
            return ((Identity[])(results[0]));
        }
        
        /// <remarks/>
        public void GetIdentitiesAsync() {
            this.GetIdentitiesAsync(null);
        }
        
        /// <remarks/>
        public void GetIdentitiesAsync(object userState) {
            if ((this.GetIdentitiesOperationCompleted == null)) {
                this.GetIdentitiesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetIdentitiesOperationCompleted);
            }
            this.InvokeAsync("GetIdentities", new object[0], this.GetIdentitiesOperationCompleted, userState);
        }
        
        private void OnGetIdentitiesOperationCompleted(object arg) {
            if ((this.GetIdentitiesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetIdentitiesCompleted(this, new GetIdentitiesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://24sevenOffice.com/webservices/SetIdentity", RequestNamespace="http://24sevenOffice.com/webservices", ResponseNamespace="http://24sevenOffice.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SetIdentity(Identity identity) {
            object[] results = this.Invoke("SetIdentity", new object[] {
                        identity});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SetIdentityAsync(Identity identity) {
            this.SetIdentityAsync(identity, null);
        }
        
        /// <remarks/>
        public void SetIdentityAsync(Identity identity, object userState) {
            if ((this.SetIdentityOperationCompleted == null)) {
                this.SetIdentityOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetIdentityOperationCompleted);
            }
            this.InvokeAsync("SetIdentity", new object[] {
                        identity}, this.SetIdentityOperationCompleted, userState);
        }
        
        private void OnSetIdentityOperationCompleted(object arg) {
            if ((this.SetIdentityCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetIdentityCompleted(this, new SetIdentityCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://24sevenOffice.com/webservices/SetIdentityById", RequestNamespace="http://24sevenOffice.com/webservices", ResponseNamespace="http://24sevenOffice.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SetIdentityById(System.Guid identityId) {
            object[] results = this.Invoke("SetIdentityById", new object[] {
                        identityId});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SetIdentityByIdAsync(System.Guid identityId) {
            this.SetIdentityByIdAsync(identityId, null);
        }
        
        /// <remarks/>
        public void SetIdentityByIdAsync(System.Guid identityId, object userState) {
            if ((this.SetIdentityByIdOperationCompleted == null)) {
                this.SetIdentityByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetIdentityByIdOperationCompleted);
            }
            this.InvokeAsync("SetIdentityById", new object[] {
                        identityId}, this.SetIdentityByIdOperationCompleted, userState);
        }
        
        private void OnSetIdentityByIdOperationCompleted(object arg) {
            if ((this.SetIdentityByIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetIdentityByIdCompleted(this, new SetIdentityByIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://24sevenOffice.com/webservices/GetIdentitiesWithCredential", RequestNamespace="http://24sevenOffice.com/webservices", ResponseNamespace="http://24sevenOffice.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Identity[] GetIdentitiesWithCredential(Credential credential) {
            object[] results = this.Invoke("GetIdentitiesWithCredential", new object[] {
                        credential});
            return ((Identity[])(results[0]));
        }
        
        /// <remarks/>
        public void GetIdentitiesWithCredentialAsync(Credential credential) {
            this.GetIdentitiesWithCredentialAsync(credential, null);
        }
        
        /// <remarks/>
        public void GetIdentitiesWithCredentialAsync(Credential credential, object userState) {
            if ((this.GetIdentitiesWithCredentialOperationCompleted == null)) {
                this.GetIdentitiesWithCredentialOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetIdentitiesWithCredentialOperationCompleted);
            }
            this.InvokeAsync("GetIdentitiesWithCredential", new object[] {
                        credential}, this.GetIdentitiesWithCredentialOperationCompleted, userState);
        }
        
        private void OnGetIdentitiesWithCredentialOperationCompleted(object arg) {
            if ((this.GetIdentitiesWithCredentialCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetIdentitiesWithCredentialCompleted(this, new GetIdentitiesWithCredentialCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://24sevenOffice.com/webservices/GetIdentitiesWithCredentialByService", RequestNamespace="http://24sevenOffice.com/webservices", ResponseNamespace="http://24sevenOffice.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Identity[] GetIdentitiesWithCredentialByService(Credential credential, int serviceId) {
            object[] results = this.Invoke("GetIdentitiesWithCredentialByService", new object[] {
                        credential,
                        serviceId});
            return ((Identity[])(results[0]));
        }
        
        /// <remarks/>
        public void GetIdentitiesWithCredentialByServiceAsync(Credential credential, int serviceId) {
            this.GetIdentitiesWithCredentialByServiceAsync(credential, serviceId, null);
        }
        
        /// <remarks/>
        public void GetIdentitiesWithCredentialByServiceAsync(Credential credential, int serviceId, object userState) {
            if ((this.GetIdentitiesWithCredentialByServiceOperationCompleted == null)) {
                this.GetIdentitiesWithCredentialByServiceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetIdentitiesWithCredentialByServiceOperationCompleted);
            }
            this.InvokeAsync("GetIdentitiesWithCredentialByService", new object[] {
                        credential,
                        serviceId}, this.GetIdentitiesWithCredentialByServiceOperationCompleted, userState);
        }
        
        private void OnGetIdentitiesWithCredentialByServiceOperationCompleted(object arg) {
            if ((this.GetIdentitiesWithCredentialByServiceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetIdentitiesWithCredentialByServiceCompleted(this, new GetIdentitiesWithCredentialByServiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public partial class Token {
        
        private System.Guid applicationIdField;
        
        private System.Guid idField;
        
        /// <remarks/>
        public System.Guid ApplicationId {
            get {
                return this.applicationIdField;
            }
            set {
                this.applicationIdField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public partial class Credential {
        
        private System.Guid applicationIdField;
        
        private System.Guid identityIdField;
        
        private string passwordField;
        
        private string usernameField;
        
        /// <remarks/>
        public System.Guid ApplicationId {
            get {
                return this.applicationIdField;
            }
            set {
                this.applicationIdField = value;
            }
        }
        
        /// <remarks/>
        // CODEGEN Warning: DefaultValue attribute on members of type System.Guid is not supported in this version of the .Net Framework.
        // CODEGEN Warning: 'default' attribute on items of type 'guid' is not supported in this version of the .Net Framework.  Ignoring default='00000000-0000-0000-0000-000000000000' attribute.
        public System.Guid IdentityId {
            get {
                return this.identityIdField;
            }
            set {
                this.identityIdField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public partial class Server {
        
        private int idField;
        
        private int typeField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public partial class Client {
        
        private long idField;
        
        private string nameField;
        
        /// <remarks/>
        public long Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public partial class User {
        
        private int contactIdField;
        
        private System.Guid idField;
        
        private string nameField;
        
        private int employeeIdField;
        
        public User() {
            this.contactIdField = -2147483648;
            this.nameField = "";
            this.employeeIdField = -2147483648;
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int ContactId {
            get {
                return this.contactIdField;
            }
            set {
                this.contactIdField = value;
            }
        }
        
        /// <remarks/>
        // CODEGEN Warning: DefaultValue attribute on members of type System.Guid is not supported in this version of the .Net Framework.
        // CODEGEN Warning: 'default' attribute on items of type 'guid' is not supported in this version of the .Net Framework.  Ignoring default='00000000-0000-0000-0000-000000000000' attribute.
        public System.Guid Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("")]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int EmployeeId {
            get {
                return this.employeeIdField;
            }
            set {
                this.employeeIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public partial class Identity {
        
        private System.Guid idField;
        
        private User userField;
        
        private Client clientField;
        
        private bool isCurrentField;
        
        private bool isDefaultField;
        
        private bool isProtectedField;
        
        private Server[] serversField;
        
        private bool isDisabledField;
        
        public Identity() {
            this.isDisabledField = false;
        }
        
        /// <remarks/>
        public System.Guid Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public User User {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
            }
        }
        
        /// <remarks/>
        public Client Client {
            get {
                return this.clientField;
            }
            set {
                this.clientField = value;
            }
        }
        
        /// <remarks/>
        public bool IsCurrent {
            get {
                return this.isCurrentField;
            }
            set {
                this.isCurrentField = value;
            }
        }
        
        /// <remarks/>
        public bool IsDefault {
            get {
                return this.isDefaultField;
            }
            set {
                this.isDefaultField = value;
            }
        }
        
        /// <remarks/>
        public bool IsProtected {
            get {
                return this.isProtectedField;
            }
            set {
                this.isProtectedField = value;
            }
        }
        
        /// <remarks/>
        public Server[] Servers {
            get {
                return this.serversField;
            }
            set {
                this.serversField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool IsDisabled {
            get {
                return this.isDisabledField;
            }
            set {
                this.isDisabledField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public partial class Passport {
        
        private System.Guid idField;
        
        private string emailField;
        
        private Identity[] identitiesField;
        
        private string sessionIdField;
        
        /// <remarks/>
        public System.Guid Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public Identity[] Identities {
            get {
                return this.identitiesField;
            }
            set {
                this.identitiesField = value;
            }
        }
        
        /// <remarks/>
        public string SessionId {
            get {
                return this.sessionIdField;
            }
            set {
                this.sessionIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void AuthenticateByTokenCompletedEventHandler(object sender, AuthenticateByTokenCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AuthenticateByTokenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AuthenticateByTokenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Passport Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Passport)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void LoginCompletedEventHandler(object sender, LoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void HasSessionCompletedEventHandler(object sender, HasSessionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HasSessionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HasSessionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetIdentityCompletedEventHandler(object sender, GetIdentityCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetIdentityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetIdentityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Identity Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Identity)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetIdentitiesCompletedEventHandler(object sender, GetIdentitiesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetIdentitiesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetIdentitiesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Identity[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Identity[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void SetIdentityCompletedEventHandler(object sender, SetIdentityCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetIdentityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetIdentityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void SetIdentityByIdCompletedEventHandler(object sender, SetIdentityByIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetIdentityByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetIdentityByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetIdentitiesWithCredentialCompletedEventHandler(object sender, GetIdentitiesWithCredentialCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetIdentitiesWithCredentialCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetIdentitiesWithCredentialCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Identity[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Identity[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetIdentitiesWithCredentialByServiceCompletedEventHandler(object sender, GetIdentitiesWithCredentialByServiceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetIdentitiesWithCredentialByServiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetIdentitiesWithCredentialByServiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Identity[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Identity[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591