//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace in24seven.projectRef {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ProjectServiceSoap", Namespace="http://24sevenOffice.com/webservices")]
    public partial class ProjectService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetProjectNameListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetProjectListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetProjectsDetailedOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSingleProjectOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetProjectTasksOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveProjectTaskOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMyProjectTasksOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetProjectRolesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetProjectTypesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetProjectStatusesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPipeLinesOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveProjectOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ProjectService() {
            this.Url = global::in24seven.Properties.Settings.Default.in24seven_projectRef_ProjectService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetProjectNameListCompletedEventHandler GetProjectNameListCompleted;
        
        /// <remarks/>
        public event GetProjectListCompletedEventHandler GetProjectListCompleted;
        
        /// <remarks/>
        public event GetProjectsDetailedCompletedEventHandler GetProjectsDetailedCompleted;
        
        /// <remarks/>
        public event GetSingleProjectCompletedEventHandler GetSingleProjectCompleted;
        
        /// <remarks/>
        public event GetProjectTasksCompletedEventHandler GetProjectTasksCompleted;
        
        /// <remarks/>
        public event SaveProjectTaskCompletedEventHandler SaveProjectTaskCompleted;
        
        /// <remarks/>
        public event GetMyProjectTasksCompletedEventHandler GetMyProjectTasksCompleted;
        
        /// <remarks/>
        public event GetProjectRolesCompletedEventHandler GetProjectRolesCompleted;
        
        /// <remarks/>
        public event GetProjectTypesCompletedEventHandler GetProjectTypesCompleted;
        
        /// <remarks/>
        public event GetProjectStatusesCompletedEventHandler GetProjectStatusesCompleted;
        
        /// <remarks/>
        public event GetPipeLinesCompletedEventHandler GetPipeLinesCompleted;
        
        /// <remarks/>
        public event SaveProjectCompletedEventHandler SaveProjectCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://24sevenOffice.com/webservices/GetProjectNameList", RequestNamespace="http://24sevenOffice.com/webservices", ResponseNamespace="http://24sevenOffice.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ProjectShort[] GetProjectNameList() {
            object[] results = this.Invoke("GetProjectNameList", new object[0]);
            return ((ProjectShort[])(results[0]));
        }
        
        /// <remarks/>
        public void GetProjectNameListAsync() {
            this.GetProjectNameListAsync(null);
        }
        
        /// <remarks/>
        public void GetProjectNameListAsync(object userState) {
            if ((this.GetProjectNameListOperationCompleted == null)) {
                this.GetProjectNameListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProjectNameListOperationCompleted);
            }
            this.InvokeAsync("GetProjectNameList", new object[0], this.GetProjectNameListOperationCompleted, userState);
        }
        
        private void OnGetProjectNameListOperationCompleted(object arg) {
            if ((this.GetProjectNameListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetProjectNameListCompleted(this, new GetProjectNameListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://24sevenOffice.com/webservices/GetProjectList", RequestNamespace="http://24sevenOffice.com/webservices", ResponseNamespace="http://24sevenOffice.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Project[] GetProjectList(ProjectSearch Ps) {
            object[] results = this.Invoke("GetProjectList", new object[] {
                        Ps});
            return ((Project[])(results[0]));
        }
        
        /// <remarks/>
        public void GetProjectListAsync(ProjectSearch Ps) {
            this.GetProjectListAsync(Ps, null);
        }
        
        /// <remarks/>
        public void GetProjectListAsync(ProjectSearch Ps, object userState) {
            if ((this.GetProjectListOperationCompleted == null)) {
                this.GetProjectListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProjectListOperationCompleted);
            }
            this.InvokeAsync("GetProjectList", new object[] {
                        Ps}, this.GetProjectListOperationCompleted, userState);
        }
        
        private void OnGetProjectListOperationCompleted(object arg) {
            if ((this.GetProjectListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetProjectListCompleted(this, new GetProjectListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://24sevenOffice.com/webservices/GetProjectsDetailed", RequestNamespace="http://24sevenOffice.com/webservices", ResponseNamespace="http://24sevenOffice.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Project[] GetProjectsDetailed(ProjectSearch Ps) {
            object[] results = this.Invoke("GetProjectsDetailed", new object[] {
                        Ps});
            return ((Project[])(results[0]));
        }
        
        /// <remarks/>
        public void GetProjectsDetailedAsync(ProjectSearch Ps) {
            this.GetProjectsDetailedAsync(Ps, null);
        }
        
        /// <remarks/>
        public void GetProjectsDetailedAsync(ProjectSearch Ps, object userState) {
            if ((this.GetProjectsDetailedOperationCompleted == null)) {
                this.GetProjectsDetailedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProjectsDetailedOperationCompleted);
            }
            this.InvokeAsync("GetProjectsDetailed", new object[] {
                        Ps}, this.GetProjectsDetailedOperationCompleted, userState);
        }
        
        private void OnGetProjectsDetailedOperationCompleted(object arg) {
            if ((this.GetProjectsDetailedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetProjectsDetailedCompleted(this, new GetProjectsDetailedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://24sevenOffice.com/webservices/GetSingleProject", RequestNamespace="http://24sevenOffice.com/webservices", ResponseNamespace="http://24sevenOffice.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Project GetSingleProject(int projectId) {
            object[] results = this.Invoke("GetSingleProject", new object[] {
                        projectId});
            return ((Project)(results[0]));
        }
        
        /// <remarks/>
        public void GetSingleProjectAsync(int projectId) {
            this.GetSingleProjectAsync(projectId, null);
        }
        
        /// <remarks/>
        public void GetSingleProjectAsync(int projectId, object userState) {
            if ((this.GetSingleProjectOperationCompleted == null)) {
                this.GetSingleProjectOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSingleProjectOperationCompleted);
            }
            this.InvokeAsync("GetSingleProject", new object[] {
                        projectId}, this.GetSingleProjectOperationCompleted, userState);
        }
        
        private void OnGetSingleProjectOperationCompleted(object arg) {
            if ((this.GetSingleProjectCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSingleProjectCompleted(this, new GetSingleProjectCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://24sevenOffice.com/webservices/GetProjectTasks", RequestNamespace="http://24sevenOffice.com/webservices", ResponseNamespace="http://24sevenOffice.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Task[] GetProjectTasks(int projectId) {
            object[] results = this.Invoke("GetProjectTasks", new object[] {
                        projectId});
            return ((Task[])(results[0]));
        }
        
        /// <remarks/>
        public void GetProjectTasksAsync(int projectId) {
            this.GetProjectTasksAsync(projectId, null);
        }
        
        /// <remarks/>
        public void GetProjectTasksAsync(int projectId, object userState) {
            if ((this.GetProjectTasksOperationCompleted == null)) {
                this.GetProjectTasksOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProjectTasksOperationCompleted);
            }
            this.InvokeAsync("GetProjectTasks", new object[] {
                        projectId}, this.GetProjectTasksOperationCompleted, userState);
        }
        
        private void OnGetProjectTasksOperationCompleted(object arg) {
            if ((this.GetProjectTasksCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetProjectTasksCompleted(this, new GetProjectTasksCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://24sevenOffice.com/webservices/SaveProjectTask", RequestNamespace="http://24sevenOffice.com/webservices", ResponseNamespace="http://24sevenOffice.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int SaveProjectTask(Task task) {
            object[] results = this.Invoke("SaveProjectTask", new object[] {
                        task});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void SaveProjectTaskAsync(Task task) {
            this.SaveProjectTaskAsync(task, null);
        }
        
        /// <remarks/>
        public void SaveProjectTaskAsync(Task task, object userState) {
            if ((this.SaveProjectTaskOperationCompleted == null)) {
                this.SaveProjectTaskOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveProjectTaskOperationCompleted);
            }
            this.InvokeAsync("SaveProjectTask", new object[] {
                        task}, this.SaveProjectTaskOperationCompleted, userState);
        }
        
        private void OnSaveProjectTaskOperationCompleted(object arg) {
            if ((this.SaveProjectTaskCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveProjectTaskCompleted(this, new SaveProjectTaskCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://24sevenOffice.com/webservices/GetMyProjectTasks", RequestNamespace="http://24sevenOffice.com/webservices", ResponseNamespace="http://24sevenOffice.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Task[] GetMyProjectTasks() {
            object[] results = this.Invoke("GetMyProjectTasks", new object[0]);
            return ((Task[])(results[0]));
        }
        
        /// <remarks/>
        public void GetMyProjectTasksAsync() {
            this.GetMyProjectTasksAsync(null);
        }
        
        /// <remarks/>
        public void GetMyProjectTasksAsync(object userState) {
            if ((this.GetMyProjectTasksOperationCompleted == null)) {
                this.GetMyProjectTasksOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMyProjectTasksOperationCompleted);
            }
            this.InvokeAsync("GetMyProjectTasks", new object[0], this.GetMyProjectTasksOperationCompleted, userState);
        }
        
        private void OnGetMyProjectTasksOperationCompleted(object arg) {
            if ((this.GetMyProjectTasksCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMyProjectTasksCompleted(this, new GetMyProjectTasksCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://24sevenOffice.com/webservices/GetProjectRoles", RequestNamespace="http://24sevenOffice.com/webservices", ResponseNamespace="http://24sevenOffice.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Role[] GetProjectRoles() {
            object[] results = this.Invoke("GetProjectRoles", new object[0]);
            return ((Role[])(results[0]));
        }
        
        /// <remarks/>
        public void GetProjectRolesAsync() {
            this.GetProjectRolesAsync(null);
        }
        
        /// <remarks/>
        public void GetProjectRolesAsync(object userState) {
            if ((this.GetProjectRolesOperationCompleted == null)) {
                this.GetProjectRolesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProjectRolesOperationCompleted);
            }
            this.InvokeAsync("GetProjectRoles", new object[0], this.GetProjectRolesOperationCompleted, userState);
        }
        
        private void OnGetProjectRolesOperationCompleted(object arg) {
            if ((this.GetProjectRolesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetProjectRolesCompleted(this, new GetProjectRolesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://24sevenOffice.com/webservices/GetProjectTypes", RequestNamespace="http://24sevenOffice.com/webservices", ResponseNamespace="http://24sevenOffice.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public KeyValuePair[] GetProjectTypes() {
            object[] results = this.Invoke("GetProjectTypes", new object[0]);
            return ((KeyValuePair[])(results[0]));
        }
        
        /// <remarks/>
        public void GetProjectTypesAsync() {
            this.GetProjectTypesAsync(null);
        }
        
        /// <remarks/>
        public void GetProjectTypesAsync(object userState) {
            if ((this.GetProjectTypesOperationCompleted == null)) {
                this.GetProjectTypesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProjectTypesOperationCompleted);
            }
            this.InvokeAsync("GetProjectTypes", new object[0], this.GetProjectTypesOperationCompleted, userState);
        }
        
        private void OnGetProjectTypesOperationCompleted(object arg) {
            if ((this.GetProjectTypesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetProjectTypesCompleted(this, new GetProjectTypesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://24sevenOffice.com/webservices/GetProjectStatuses", RequestNamespace="http://24sevenOffice.com/webservices", ResponseNamespace="http://24sevenOffice.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Status[] GetProjectStatuses() {
            object[] results = this.Invoke("GetProjectStatuses", new object[0]);
            return ((Status[])(results[0]));
        }
        
        /// <remarks/>
        public void GetProjectStatusesAsync() {
            this.GetProjectStatusesAsync(null);
        }
        
        /// <remarks/>
        public void GetProjectStatusesAsync(object userState) {
            if ((this.GetProjectStatusesOperationCompleted == null)) {
                this.GetProjectStatusesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProjectStatusesOperationCompleted);
            }
            this.InvokeAsync("GetProjectStatuses", new object[0], this.GetProjectStatusesOperationCompleted, userState);
        }
        
        private void OnGetProjectStatusesOperationCompleted(object arg) {
            if ((this.GetProjectStatusesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetProjectStatusesCompleted(this, new GetProjectStatusesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://24sevenOffice.com/webservices/GetPipeLines", RequestNamespace="http://24sevenOffice.com/webservices", ResponseNamespace="http://24sevenOffice.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public KeyValuePair[] GetPipeLines() {
            object[] results = this.Invoke("GetPipeLines", new object[0]);
            return ((KeyValuePair[])(results[0]));
        }
        
        /// <remarks/>
        public void GetPipeLinesAsync() {
            this.GetPipeLinesAsync(null);
        }
        
        /// <remarks/>
        public void GetPipeLinesAsync(object userState) {
            if ((this.GetPipeLinesOperationCompleted == null)) {
                this.GetPipeLinesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPipeLinesOperationCompleted);
            }
            this.InvokeAsync("GetPipeLines", new object[0], this.GetPipeLinesOperationCompleted, userState);
        }
        
        private void OnGetPipeLinesOperationCompleted(object arg) {
            if ((this.GetPipeLinesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPipeLinesCompleted(this, new GetPipeLinesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://24sevenOffice.com/webservices/SaveProject", RequestNamespace="http://24sevenOffice.com/webservices", ResponseNamespace="http://24sevenOffice.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int SaveProject(Project project) {
            object[] results = this.Invoke("SaveProject", new object[] {
                        project});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void SaveProjectAsync(Project project) {
            this.SaveProjectAsync(project, null);
        }
        
        /// <remarks/>
        public void SaveProjectAsync(Project project, object userState) {
            if ((this.SaveProjectOperationCompleted == null)) {
                this.SaveProjectOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveProjectOperationCompleted);
            }
            this.InvokeAsync("SaveProject", new object[] {
                        project}, this.SaveProjectOperationCompleted, userState);
        }
        
        private void OnSaveProjectOperationCompleted(object arg) {
            if ((this.SaveProjectCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveProjectCompleted(this, new SaveProjectCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public partial class ProjectShort {
        
        private int idField;
        
        private string nameField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public partial class Status {
        
        private int idField;
        
        private string nameField;
        
        private bool activeField;
        
        public Status() {
            this.idField = -2147483648;
            this.nameField = "";
            this.activeField = true;
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("")]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool Active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public partial class KeyValuePair {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public partial class Role {
        
        private int idField;
        
        private string nameField;
        
        private int parentField;
        
        public Role() {
            this.idField = -2147483648;
            this.nameField = "";
            this.parentField = -2147483648;
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("")]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int Parent {
            get {
                return this.parentField;
            }
            set {
                this.parentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public partial class Task {
        
        private int idField;
        
        private string nameField;
        
        private string descriptionField;
        
        private System.DateTime dateStartField;
        
        private System.DateTime dateStopField;
        
        private decimal overtimeField;
        
        private int parentField;
        
        private int priorityField;
        
        private int projectField;
        
        private int projectLinkField;
        
        private System.Nullable<int> statusField;
        
        private int workTypeIdField;
        
        private int estimateField;
        
        private decimal registeredField;
        
        private int[] participantsField;
        
        public Task() {
            this.idField = -2147483648;
            this.nameField = "";
            this.descriptionField = "";
            this.dateStartField = new System.DateTime(0);
            this.dateStopField = new System.DateTime(0);
            this.overtimeField = ((decimal)(-79228162514264337593543950335m));
            this.parentField = -2147483648;
            this.priorityField = -2147483648;
            this.projectField = -2147483648;
            this.projectLinkField = -2147483648;
            this.workTypeIdField = -2147483648;
            this.estimateField = -2147483648;
            this.registeredField = ((decimal)(-79228162514264337593543950335m));
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("")]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("")]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(System.DateTime), "0001-01-01T00:00:00")]
        public System.DateTime DateStart {
            get {
                return this.dateStartField;
            }
            set {
                this.dateStartField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(System.DateTime), "0001-01-01T00:00:00")]
        public System.DateTime DateStop {
            get {
                return this.dateStopField;
            }
            set {
                this.dateStopField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "-79228162514264337593543950335")]
        public decimal Overtime {
            get {
                return this.overtimeField;
            }
            set {
                this.overtimeField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int Parent {
            get {
                return this.parentField;
            }
            set {
                this.parentField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int Priority {
            get {
                return this.priorityField;
            }
            set {
                this.priorityField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int Project {
            get {
                return this.projectField;
            }
            set {
                this.projectField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int ProjectLink {
            get {
                return this.projectLinkField;
            }
            set {
                this.projectLinkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int WorkTypeId {
            get {
                return this.workTypeIdField;
            }
            set {
                this.workTypeIdField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int Estimate {
            get {
                return this.estimateField;
            }
            set {
                this.estimateField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "-79228162514264337593543950335")]
        public decimal Registered {
            get {
                return this.registeredField;
            }
            set {
                this.registeredField = value;
            }
        }
        
        /// <remarks/>
        public int[] Participants {
            get {
                return this.participantsField;
            }
            set {
                this.participantsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public partial class Project {
        
        private int idField;
        
        private bool enabledField;
        
        private string nameField;
        
        private string rawNameField;
        
        private ProjectNameType nameDisplayField;
        
        private bool quickListedField;
        
        private System.DateTime dateChangedField;
        
        private System.DateTime dateStartField;
        
        private System.DateTime dateStopField;
        
        private int customerIdField;
        
        private string customerNameField;
        
        private int ownerField;
        
        private int pipelineField;
        
        private int typeIdField;
        
        private string typeNameField;
        
        private int statusIdField;
        
        private string statusNameField;
        
        private TriState needApprovalField;
        
        private bool multiCustomerField;
        
        private string descriptionField;
        
        private int workTypeIdField;
        
        private string workTypeNameField;
        
        private TimeRegType timeRegField;
        
        private short versionField;
        
        private TriState isFoldersAddedField;
        
        private TriState overrideWorkTypeTaskField;
        
        private int[] participantsField;
        
        public Project() {
            this.idField = -2147483648;
            this.enabledField = false;
            this.nameField = "";
            this.rawNameField = "";
            this.quickListedField = true;
            this.dateChangedField = new System.DateTime(0);
            this.dateStartField = new System.DateTime(0);
            this.dateStopField = new System.DateTime(0);
            this.customerIdField = -2147483648;
            this.customerNameField = "";
            this.ownerField = -2147483648;
            this.pipelineField = -2147483648;
            this.typeIdField = -2147483648;
            this.typeNameField = "";
            this.statusIdField = -2147483648;
            this.statusNameField = "";
            this.needApprovalField = TriState.none;
            this.multiCustomerField = false;
            this.descriptionField = "";
            this.workTypeIdField = -2147483648;
            this.workTypeNameField = "";
            this.versionField = ((short)(-32768));
            this.isFoldersAddedField = TriState.none;
            this.overrideWorkTypeTaskField = TriState.none;
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Enabled {
            get {
                return this.enabledField;
            }
            set {
                this.enabledField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("")]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("")]
        public string RawName {
            get {
                return this.rawNameField;
            }
            set {
                this.rawNameField = value;
            }
        }
        
        /// <remarks/>
        public ProjectNameType NameDisplay {
            get {
                return this.nameDisplayField;
            }
            set {
                this.nameDisplayField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool QuickListed {
            get {
                return this.quickListedField;
            }
            set {
                this.quickListedField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(System.DateTime), "0001-01-01T00:00:00")]
        public System.DateTime DateChanged {
            get {
                return this.dateChangedField;
            }
            set {
                this.dateChangedField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(System.DateTime), "0001-01-01T00:00:00")]
        public System.DateTime DateStart {
            get {
                return this.dateStartField;
            }
            set {
                this.dateStartField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(System.DateTime), "0001-01-01T00:00:00")]
        public System.DateTime DateStop {
            get {
                return this.dateStopField;
            }
            set {
                this.dateStopField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int CustomerId {
            get {
                return this.customerIdField;
            }
            set {
                this.customerIdField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("")]
        public string CustomerName {
            get {
                return this.customerNameField;
            }
            set {
                this.customerNameField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int Owner {
            get {
                return this.ownerField;
            }
            set {
                this.ownerField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int Pipeline {
            get {
                return this.pipelineField;
            }
            set {
                this.pipelineField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int TypeId {
            get {
                return this.typeIdField;
            }
            set {
                this.typeIdField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("")]
        public string TypeName {
            get {
                return this.typeNameField;
            }
            set {
                this.typeNameField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int StatusId {
            get {
                return this.statusIdField;
            }
            set {
                this.statusIdField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("")]
        public string StatusName {
            get {
                return this.statusNameField;
            }
            set {
                this.statusNameField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(TriState.none)]
        public TriState NeedApproval {
            get {
                return this.needApprovalField;
            }
            set {
                this.needApprovalField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool MultiCustomer {
            get {
                return this.multiCustomerField;
            }
            set {
                this.multiCustomerField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("")]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int WorkTypeId {
            get {
                return this.workTypeIdField;
            }
            set {
                this.workTypeIdField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("")]
        public string WorkTypeName {
            get {
                return this.workTypeNameField;
            }
            set {
                this.workTypeNameField = value;
            }
        }
        
        /// <remarks/>
        public TimeRegType TimeReg {
            get {
                return this.timeRegField;
            }
            set {
                this.timeRegField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(short), "-32768")]
        public short Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(TriState.none)]
        public TriState IsFoldersAdded {
            get {
                return this.isFoldersAddedField;
            }
            set {
                this.isFoldersAddedField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(TriState.none)]
        public TriState OverrideWorkTypeTask {
            get {
                return this.overrideWorkTypeTaskField;
            }
            set {
                this.overrideWorkTypeTaskField = value;
            }
        }
        
        /// <remarks/>
        public int[] Participants {
            get {
                return this.participantsField;
            }
            set {
                this.participantsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public enum ProjectNameType {
        
        /// <remarks/>
        Plain,
        
        /// <remarks/>
        Company_Project,
        
        /// <remarks/>
        Project_Company,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public enum TriState {
        
        /// <remarks/>
        none,
        
        /// <remarks/>
        True,
        
        /// <remarks/>
        False,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public enum TimeRegType {
        
        /// <remarks/>
        WorkType,
        
        /// <remarks/>
        Task,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public partial class ProjectSearch {
        
        private bool myProjectsField;
        
        private bool allOpenProjectsField;
        
        private int customerIdField;
        
        private string searchField;
        
        private System.DateTime changedAfterField;
        
        private System.DateTime startedAfterField;
        
        private System.DateTime startedBeforeField;
        
        public ProjectSearch() {
            this.myProjectsField = false;
            this.allOpenProjectsField = false;
            this.customerIdField = -2147483648;
            this.searchField = "";
            this.changedAfterField = new System.DateTime(0);
            this.startedAfterField = new System.DateTime(0);
            this.startedBeforeField = new System.DateTime(0);
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool MyProjects {
            get {
                return this.myProjectsField;
            }
            set {
                this.myProjectsField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool AllOpenProjects {
            get {
                return this.allOpenProjectsField;
            }
            set {
                this.allOpenProjectsField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int CustomerId {
            get {
                return this.customerIdField;
            }
            set {
                this.customerIdField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("")]
        public string Search {
            get {
                return this.searchField;
            }
            set {
                this.searchField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(System.DateTime), "0001-01-01T00:00:00")]
        public System.DateTime ChangedAfter {
            get {
                return this.changedAfterField;
            }
            set {
                this.changedAfterField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(System.DateTime), "0001-01-01T00:00:00")]
        public System.DateTime StartedAfter {
            get {
                return this.startedAfterField;
            }
            set {
                this.startedAfterField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(System.DateTime), "0001-01-01T00:00:00")]
        public System.DateTime StartedBefore {
            get {
                return this.startedBeforeField;
            }
            set {
                this.startedBeforeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetProjectNameListCompletedEventHandler(object sender, GetProjectNameListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetProjectNameListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetProjectNameListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ProjectShort[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ProjectShort[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetProjectListCompletedEventHandler(object sender, GetProjectListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetProjectListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetProjectListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Project[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Project[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetProjectsDetailedCompletedEventHandler(object sender, GetProjectsDetailedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetProjectsDetailedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetProjectsDetailedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Project[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Project[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetSingleProjectCompletedEventHandler(object sender, GetSingleProjectCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSingleProjectCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSingleProjectCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Project Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Project)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetProjectTasksCompletedEventHandler(object sender, GetProjectTasksCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetProjectTasksCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetProjectTasksCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Task[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Task[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void SaveProjectTaskCompletedEventHandler(object sender, SaveProjectTaskCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveProjectTaskCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveProjectTaskCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetMyProjectTasksCompletedEventHandler(object sender, GetMyProjectTasksCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMyProjectTasksCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMyProjectTasksCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Task[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Task[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetProjectRolesCompletedEventHandler(object sender, GetProjectRolesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetProjectRolesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetProjectRolesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Role[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Role[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetProjectTypesCompletedEventHandler(object sender, GetProjectTypesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetProjectTypesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetProjectTypesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public KeyValuePair[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((KeyValuePair[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetProjectStatusesCompletedEventHandler(object sender, GetProjectStatusesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetProjectStatusesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetProjectStatusesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Status[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Status[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetPipeLinesCompletedEventHandler(object sender, GetPipeLinesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPipeLinesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPipeLinesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public KeyValuePair[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((KeyValuePair[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void SaveProjectCompletedEventHandler(object sender, SaveProjectCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveProjectCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveProjectCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591