//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace in24seven.personRef {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PersonServiceSoap", Namespace="http://24sevenOffice.com/webservices")]
    public partial class PersonService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private Authentication authenticationValueField;
        
        private System.Threading.SendOrPostCallback GetPersonIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback SavePersonOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPersonIdsByUserNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPersonIdByCompanyIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPersonsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPersonsDetailedOperationCompleted;
        
        private System.Threading.SendOrPostCallback MakeRelationOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRelationsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRelationsChangedAfterOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteRelationOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetNotesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllNotesOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddNoteOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteNoteOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteNoteByIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCategoryListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPersonCategoryListOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddCategoryToPersonOperationCompleted;
        
        private System.Threading.SendOrPostCallback RemoveCategoryFromPersonOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public PersonService() {
            this.Url = global::in24seven.Properties.Settings.Default.in24seven_personRef_PersonService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public Authentication AuthenticationValue {
            get {
                return this.authenticationValueField;
            }
            set {
                this.authenticationValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetPersonIdCompletedEventHandler GetPersonIdCompleted;
        
        /// <remarks/>
        public event SavePersonCompletedEventHandler SavePersonCompleted;
        
        /// <remarks/>
        public event GetPersonIdsByUserNameCompletedEventHandler GetPersonIdsByUserNameCompleted;
        
        /// <remarks/>
        public event GetPersonIdByCompanyIdCompletedEventHandler GetPersonIdByCompanyIdCompleted;
        
        /// <remarks/>
        public event GetPersonsCompletedEventHandler GetPersonsCompleted;
        
        /// <remarks/>
        public event GetPersonsDetailedCompletedEventHandler GetPersonsDetailedCompleted;
        
        /// <remarks/>
        public event MakeRelationCompletedEventHandler MakeRelationCompleted;
        
        /// <remarks/>
        public event GetRelationsCompletedEventHandler GetRelationsCompleted;
        
        /// <remarks/>
        public event GetRelationsChangedAfterCompletedEventHandler GetRelationsChangedAfterCompleted;
        
        /// <remarks/>
        public event DeleteRelationCompletedEventHandler DeleteRelationCompleted;
        
        /// <remarks/>
        public event GetNotesCompletedEventHandler GetNotesCompleted;
        
        /// <remarks/>
        public event GetAllNotesCompletedEventHandler GetAllNotesCompleted;
        
        /// <remarks/>
        public event AddNoteCompletedEventHandler AddNoteCompleted;
        
        /// <remarks/>
        public event DeleteNoteCompletedEventHandler DeleteNoteCompleted;
        
        /// <remarks/>
        public event DeleteNoteByIdCompletedEventHandler DeleteNoteByIdCompleted;
        
        /// <remarks/>
        public event GetCategoryListCompletedEventHandler GetCategoryListCompleted;
        
        /// <remarks/>
        public event GetPersonCategoryListCompletedEventHandler GetPersonCategoryListCompleted;
        
        /// <remarks/>
        public event AddCategoryToPersonCompletedEventHandler AddCategoryToPersonCompleted;
        
        /// <remarks/>
        public event RemoveCategoryFromPersonCompletedEventHandler RemoveCategoryFromPersonCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://24sevenOffice.com/webservices/GetPersonId", RequestNamespace="http://24sevenOffice.com/webservices", ResponseNamespace="http://24sevenOffice.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long GetPersonId(string consumerPersonNo) {
            object[] results = this.Invoke("GetPersonId", new object[] {
                        consumerPersonNo});
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public void GetPersonIdAsync(string consumerPersonNo) {
            this.GetPersonIdAsync(consumerPersonNo, null);
        }
        
        /// <remarks/>
        public void GetPersonIdAsync(string consumerPersonNo, object userState) {
            if ((this.GetPersonIdOperationCompleted == null)) {
                this.GetPersonIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPersonIdOperationCompleted);
            }
            this.InvokeAsync("GetPersonId", new object[] {
                        consumerPersonNo}, this.GetPersonIdOperationCompleted, userState);
        }
        
        private void OnGetPersonIdOperationCompleted(object arg) {
            if ((this.GetPersonIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPersonIdCompleted(this, new GetPersonIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://24sevenOffice.com/webservices/SavePerson", RequestNamespace="http://24sevenOffice.com/webservices", ResponseNamespace="http://24sevenOffice.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long SavePerson(PersonItem personItem) {
            object[] results = this.Invoke("SavePerson", new object[] {
                        personItem});
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public void SavePersonAsync(PersonItem personItem) {
            this.SavePersonAsync(personItem, null);
        }
        
        /// <remarks/>
        public void SavePersonAsync(PersonItem personItem, object userState) {
            if ((this.SavePersonOperationCompleted == null)) {
                this.SavePersonOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSavePersonOperationCompleted);
            }
            this.InvokeAsync("SavePerson", new object[] {
                        personItem}, this.SavePersonOperationCompleted, userState);
        }
        
        private void OnSavePersonOperationCompleted(object arg) {
            if ((this.SavePersonCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SavePersonCompleted(this, new SavePersonCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://24sevenOffice.com/webservices/GetPersonIdsByUserName", RequestNamespace="http://24sevenOffice.com/webservices", ResponseNamespace="http://24sevenOffice.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long[] GetPersonIdsByUserName(string username) {
            object[] results = this.Invoke("GetPersonIdsByUserName", new object[] {
                        username});
            return ((long[])(results[0]));
        }
        
        /// <remarks/>
        public void GetPersonIdsByUserNameAsync(string username) {
            this.GetPersonIdsByUserNameAsync(username, null);
        }
        
        /// <remarks/>
        public void GetPersonIdsByUserNameAsync(string username, object userState) {
            if ((this.GetPersonIdsByUserNameOperationCompleted == null)) {
                this.GetPersonIdsByUserNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPersonIdsByUserNameOperationCompleted);
            }
            this.InvokeAsync("GetPersonIdsByUserName", new object[] {
                        username}, this.GetPersonIdsByUserNameOperationCompleted, userState);
        }
        
        private void OnGetPersonIdsByUserNameOperationCompleted(object arg) {
            if ((this.GetPersonIdsByUserNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPersonIdsByUserNameCompleted(this, new GetPersonIdsByUserNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://24sevenOffice.com/webservices/GetPersonIdByCompanyId", RequestNamespace="http://24sevenOffice.com/webservices", ResponseNamespace="http://24sevenOffice.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long GetPersonIdByCompanyId(int companyId) {
            object[] results = this.Invoke("GetPersonIdByCompanyId", new object[] {
                        companyId});
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public void GetPersonIdByCompanyIdAsync(int companyId) {
            this.GetPersonIdByCompanyIdAsync(companyId, null);
        }
        
        /// <remarks/>
        public void GetPersonIdByCompanyIdAsync(int companyId, object userState) {
            if ((this.GetPersonIdByCompanyIdOperationCompleted == null)) {
                this.GetPersonIdByCompanyIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPersonIdByCompanyIdOperationCompleted);
            }
            this.InvokeAsync("GetPersonIdByCompanyId", new object[] {
                        companyId}, this.GetPersonIdByCompanyIdOperationCompleted, userState);
        }
        
        private void OnGetPersonIdByCompanyIdOperationCompleted(object arg) {
            if ((this.GetPersonIdByCompanyIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPersonIdByCompanyIdCompleted(this, new GetPersonIdByCompanyIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://24sevenOffice.com/webservices/GetPersons", RequestNamespace="http://24sevenOffice.com/webservices", ResponseNamespace="http://24sevenOffice.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PersonItem[] GetPersons(PersonSearchParameters personSearch) {
            object[] results = this.Invoke("GetPersons", new object[] {
                        personSearch});
            return ((PersonItem[])(results[0]));
        }
        
        /// <remarks/>
        public void GetPersonsAsync(PersonSearchParameters personSearch) {
            this.GetPersonsAsync(personSearch, null);
        }
        
        /// <remarks/>
        public void GetPersonsAsync(PersonSearchParameters personSearch, object userState) {
            if ((this.GetPersonsOperationCompleted == null)) {
                this.GetPersonsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPersonsOperationCompleted);
            }
            this.InvokeAsync("GetPersons", new object[] {
                        personSearch}, this.GetPersonsOperationCompleted, userState);
        }
        
        private void OnGetPersonsOperationCompleted(object arg) {
            if ((this.GetPersonsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPersonsCompleted(this, new GetPersonsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://24sevenOffice.com/webservices/GetPersonsDetailed", RequestNamespace="http://24sevenOffice.com/webservices", ResponseNamespace="http://24sevenOffice.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PersonItem[] GetPersonsDetailed(PersonSearchParameters personSearch) {
            object[] results = this.Invoke("GetPersonsDetailed", new object[] {
                        personSearch});
            return ((PersonItem[])(results[0]));
        }
        
        /// <remarks/>
        public void GetPersonsDetailedAsync(PersonSearchParameters personSearch) {
            this.GetPersonsDetailedAsync(personSearch, null);
        }
        
        /// <remarks/>
        public void GetPersonsDetailedAsync(PersonSearchParameters personSearch, object userState) {
            if ((this.GetPersonsDetailedOperationCompleted == null)) {
                this.GetPersonsDetailedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPersonsDetailedOperationCompleted);
            }
            this.InvokeAsync("GetPersonsDetailed", new object[] {
                        personSearch}, this.GetPersonsDetailedOperationCompleted, userState);
        }
        
        private void OnGetPersonsDetailedOperationCompleted(object arg) {
            if ((this.GetPersonsDetailedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPersonsDetailedCompleted(this, new GetPersonsDetailedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://24sevenOffice.com/webservices/MakeRelation", RequestNamespace="http://24sevenOffice.com/webservices", ResponseNamespace="http://24sevenOffice.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool MakeRelation(RelationData relation) {
            object[] results = this.Invoke("MakeRelation", new object[] {
                        relation});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void MakeRelationAsync(RelationData relation) {
            this.MakeRelationAsync(relation, null);
        }
        
        /// <remarks/>
        public void MakeRelationAsync(RelationData relation, object userState) {
            if ((this.MakeRelationOperationCompleted == null)) {
                this.MakeRelationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMakeRelationOperationCompleted);
            }
            this.InvokeAsync("MakeRelation", new object[] {
                        relation}, this.MakeRelationOperationCompleted, userState);
        }
        
        private void OnMakeRelationOperationCompleted(object arg) {
            if ((this.MakeRelationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MakeRelationCompleted(this, new MakeRelationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://24sevenOffice.com/webservices/GetRelations", RequestNamespace="http://24sevenOffice.com/webservices", ResponseNamespace="http://24sevenOffice.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RelationData[] GetRelations(long personId) {
            object[] results = this.Invoke("GetRelations", new object[] {
                        personId});
            return ((RelationData[])(results[0]));
        }
        
        /// <remarks/>
        public void GetRelationsAsync(long personId) {
            this.GetRelationsAsync(personId, null);
        }
        
        /// <remarks/>
        public void GetRelationsAsync(long personId, object userState) {
            if ((this.GetRelationsOperationCompleted == null)) {
                this.GetRelationsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRelationsOperationCompleted);
            }
            this.InvokeAsync("GetRelations", new object[] {
                        personId}, this.GetRelationsOperationCompleted, userState);
        }
        
        private void OnGetRelationsOperationCompleted(object arg) {
            if ((this.GetRelationsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRelationsCompleted(this, new GetRelationsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://24sevenOffice.com/webservices/GetRelationsChangedAfter", RequestNamespace="http://24sevenOffice.com/webservices", ResponseNamespace="http://24sevenOffice.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RelationData[] GetRelationsChangedAfter(System.DateTime changedAfter) {
            object[] results = this.Invoke("GetRelationsChangedAfter", new object[] {
                        changedAfter});
            return ((RelationData[])(results[0]));
        }
        
        /// <remarks/>
        public void GetRelationsChangedAfterAsync(System.DateTime changedAfter) {
            this.GetRelationsChangedAfterAsync(changedAfter, null);
        }
        
        /// <remarks/>
        public void GetRelationsChangedAfterAsync(System.DateTime changedAfter, object userState) {
            if ((this.GetRelationsChangedAfterOperationCompleted == null)) {
                this.GetRelationsChangedAfterOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRelationsChangedAfterOperationCompleted);
            }
            this.InvokeAsync("GetRelationsChangedAfter", new object[] {
                        changedAfter}, this.GetRelationsChangedAfterOperationCompleted, userState);
        }
        
        private void OnGetRelationsChangedAfterOperationCompleted(object arg) {
            if ((this.GetRelationsChangedAfterCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRelationsChangedAfterCompleted(this, new GetRelationsChangedAfterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://24sevenOffice.com/webservices/DeleteRelation", RequestNamespace="http://24sevenOffice.com/webservices", ResponseNamespace="http://24sevenOffice.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DeleteRelation(long personId, long companyId) {
            this.Invoke("DeleteRelation", new object[] {
                        personId,
                        companyId});
        }
        
        /// <remarks/>
        public void DeleteRelationAsync(long personId, long companyId) {
            this.DeleteRelationAsync(personId, companyId, null);
        }
        
        /// <remarks/>
        public void DeleteRelationAsync(long personId, long companyId, object userState) {
            if ((this.DeleteRelationOperationCompleted == null)) {
                this.DeleteRelationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteRelationOperationCompleted);
            }
            this.InvokeAsync("DeleteRelation", new object[] {
                        personId,
                        companyId}, this.DeleteRelationOperationCompleted, userState);
        }
        
        private void OnDeleteRelationOperationCompleted(object arg) {
            if ((this.DeleteRelationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteRelationCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://24sevenOffice.com/webservices/GetNotes", RequestNamespace="http://24sevenOffice.com/webservices", ResponseNamespace="http://24sevenOffice.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public NoteData[] GetNotes(long personId) {
            object[] results = this.Invoke("GetNotes", new object[] {
                        personId});
            return ((NoteData[])(results[0]));
        }
        
        /// <remarks/>
        public void GetNotesAsync(long personId) {
            this.GetNotesAsync(personId, null);
        }
        
        /// <remarks/>
        public void GetNotesAsync(long personId, object userState) {
            if ((this.GetNotesOperationCompleted == null)) {
                this.GetNotesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetNotesOperationCompleted);
            }
            this.InvokeAsync("GetNotes", new object[] {
                        personId}, this.GetNotesOperationCompleted, userState);
        }
        
        private void OnGetNotesOperationCompleted(object arg) {
            if ((this.GetNotesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetNotesCompleted(this, new GetNotesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://24sevenOffice.com/webservices/GetAllNotes", RequestNamespace="http://24sevenOffice.com/webservices", ResponseNamespace="http://24sevenOffice.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public NoteData[] GetAllNotes() {
            object[] results = this.Invoke("GetAllNotes", new object[0]);
            return ((NoteData[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllNotesAsync() {
            this.GetAllNotesAsync(null);
        }
        
        /// <remarks/>
        public void GetAllNotesAsync(object userState) {
            if ((this.GetAllNotesOperationCompleted == null)) {
                this.GetAllNotesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllNotesOperationCompleted);
            }
            this.InvokeAsync("GetAllNotes", new object[0], this.GetAllNotesOperationCompleted, userState);
        }
        
        private void OnGetAllNotesOperationCompleted(object arg) {
            if ((this.GetAllNotesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllNotesCompleted(this, new GetAllNotesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://24sevenOffice.com/webservices/AddNote", RequestNamespace="http://24sevenOffice.com/webservices", ResponseNamespace="http://24sevenOffice.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int AddNote(NoteData note) {
            object[] results = this.Invoke("AddNote", new object[] {
                        note});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void AddNoteAsync(NoteData note) {
            this.AddNoteAsync(note, null);
        }
        
        /// <remarks/>
        public void AddNoteAsync(NoteData note, object userState) {
            if ((this.AddNoteOperationCompleted == null)) {
                this.AddNoteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddNoteOperationCompleted);
            }
            this.InvokeAsync("AddNote", new object[] {
                        note}, this.AddNoteOperationCompleted, userState);
        }
        
        private void OnAddNoteOperationCompleted(object arg) {
            if ((this.AddNoteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddNoteCompleted(this, new AddNoteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://24sevenOffice.com/webservices/DeleteNote", RequestNamespace="http://24sevenOffice.com/webservices", ResponseNamespace="http://24sevenOffice.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DeleteNote(NoteData note) {
            this.Invoke("DeleteNote", new object[] {
                        note});
        }
        
        /// <remarks/>
        public void DeleteNoteAsync(NoteData note) {
            this.DeleteNoteAsync(note, null);
        }
        
        /// <remarks/>
        public void DeleteNoteAsync(NoteData note, object userState) {
            if ((this.DeleteNoteOperationCompleted == null)) {
                this.DeleteNoteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteNoteOperationCompleted);
            }
            this.InvokeAsync("DeleteNote", new object[] {
                        note}, this.DeleteNoteOperationCompleted, userState);
        }
        
        private void OnDeleteNoteOperationCompleted(object arg) {
            if ((this.DeleteNoteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteNoteCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://24sevenOffice.com/webservices/DeleteNoteById", RequestNamespace="http://24sevenOffice.com/webservices", ResponseNamespace="http://24sevenOffice.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DeleteNoteById(int noteId) {
            this.Invoke("DeleteNoteById", new object[] {
                        noteId});
        }
        
        /// <remarks/>
        public void DeleteNoteByIdAsync(int noteId) {
            this.DeleteNoteByIdAsync(noteId, null);
        }
        
        /// <remarks/>
        public void DeleteNoteByIdAsync(int noteId, object userState) {
            if ((this.DeleteNoteByIdOperationCompleted == null)) {
                this.DeleteNoteByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteNoteByIdOperationCompleted);
            }
            this.InvokeAsync("DeleteNoteById", new object[] {
                        noteId}, this.DeleteNoteByIdOperationCompleted, userState);
        }
        
        private void OnDeleteNoteByIdOperationCompleted(object arg) {
            if ((this.DeleteNoteByIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteNoteByIdCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://24sevenOffice.com/webservices/GetCategoryList", RequestNamespace="http://24sevenOffice.com/webservices", ResponseNamespace="http://24sevenOffice.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Category[] GetCategoryList() {
            object[] results = this.Invoke("GetCategoryList", new object[0]);
            return ((Category[])(results[0]));
        }
        
        /// <remarks/>
        public void GetCategoryListAsync() {
            this.GetCategoryListAsync(null);
        }
        
        /// <remarks/>
        public void GetCategoryListAsync(object userState) {
            if ((this.GetCategoryListOperationCompleted == null)) {
                this.GetCategoryListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCategoryListOperationCompleted);
            }
            this.InvokeAsync("GetCategoryList", new object[0], this.GetCategoryListOperationCompleted, userState);
        }
        
        private void OnGetCategoryListOperationCompleted(object arg) {
            if ((this.GetCategoryListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCategoryListCompleted(this, new GetCategoryListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://24sevenOffice.com/webservices/GetPersonCategoryList", RequestNamespace="http://24sevenOffice.com/webservices", ResponseNamespace="http://24sevenOffice.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int[] GetPersonCategoryList(long personId) {
            object[] results = this.Invoke("GetPersonCategoryList", new object[] {
                        personId});
            return ((int[])(results[0]));
        }
        
        /// <remarks/>
        public void GetPersonCategoryListAsync(long personId) {
            this.GetPersonCategoryListAsync(personId, null);
        }
        
        /// <remarks/>
        public void GetPersonCategoryListAsync(long personId, object userState) {
            if ((this.GetPersonCategoryListOperationCompleted == null)) {
                this.GetPersonCategoryListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPersonCategoryListOperationCompleted);
            }
            this.InvokeAsync("GetPersonCategoryList", new object[] {
                        personId}, this.GetPersonCategoryListOperationCompleted, userState);
        }
        
        private void OnGetPersonCategoryListOperationCompleted(object arg) {
            if ((this.GetPersonCategoryListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPersonCategoryListCompleted(this, new GetPersonCategoryListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://24sevenOffice.com/webservices/AddCategoryToPerson", RequestNamespace="http://24sevenOffice.com/webservices", ResponseNamespace="http://24sevenOffice.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AddCategoryToPerson(long personId, int categoryId) {
            this.Invoke("AddCategoryToPerson", new object[] {
                        personId,
                        categoryId});
        }
        
        /// <remarks/>
        public void AddCategoryToPersonAsync(long personId, int categoryId) {
            this.AddCategoryToPersonAsync(personId, categoryId, null);
        }
        
        /// <remarks/>
        public void AddCategoryToPersonAsync(long personId, int categoryId, object userState) {
            if ((this.AddCategoryToPersonOperationCompleted == null)) {
                this.AddCategoryToPersonOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddCategoryToPersonOperationCompleted);
            }
            this.InvokeAsync("AddCategoryToPerson", new object[] {
                        personId,
                        categoryId}, this.AddCategoryToPersonOperationCompleted, userState);
        }
        
        private void OnAddCategoryToPersonOperationCompleted(object arg) {
            if ((this.AddCategoryToPersonCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddCategoryToPersonCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://24sevenOffice.com/webservices/RemoveCategoryFromPerson", RequestNamespace="http://24sevenOffice.com/webservices", ResponseNamespace="http://24sevenOffice.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void RemoveCategoryFromPerson(long personId, int categoryId) {
            this.Invoke("RemoveCategoryFromPerson", new object[] {
                        personId,
                        categoryId});
        }
        
        /// <remarks/>
        public void RemoveCategoryFromPersonAsync(long personId, int categoryId) {
            this.RemoveCategoryFromPersonAsync(personId, categoryId, null);
        }
        
        /// <remarks/>
        public void RemoveCategoryFromPersonAsync(long personId, int categoryId, object userState) {
            if ((this.RemoveCategoryFromPersonOperationCompleted == null)) {
                this.RemoveCategoryFromPersonOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRemoveCategoryFromPersonOperationCompleted);
            }
            this.InvokeAsync("RemoveCategoryFromPerson", new object[] {
                        personId,
                        categoryId}, this.RemoveCategoryFromPersonOperationCompleted, userState);
        }
        
        private void OnRemoveCategoryFromPersonOperationCompleted(object arg) {
            if ((this.RemoveCategoryFromPersonCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RemoveCategoryFromPersonCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://24sevenOffice.com/webservices", IsNullable=false)]
    public partial class Authentication : System.Web.Services.Protocols.SoapHeader {
        
        private string usernameField;
        
        private string passwordField;
        
        private string userIdField;
        
        private string employeeIdField;
        
        private long consumerIdField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
            }
        }
        
        /// <remarks/>
        public string EmployeeId {
            get {
                return this.employeeIdField;
            }
            set {
                this.employeeIdField = value;
            }
        }
        
        /// <remarks/>
        public long ConsumerId {
            get {
                return this.consumerIdField;
            }
            set {
                this.consumerIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public partial class Category {
        
        private int idField;
        
        private string nameField;
        
        private string noteField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Note {
            get {
                return this.noteField;
            }
            set {
                this.noteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public partial class NoteData {
        
        private int idField;
        
        private string subjectField;
        
        private string descriptionField;
        
        private int employeeIdField;
        
        private System.DateTime dateAddedField;
        
        private System.DateTime dateField;
        
        private long personIdField;
        
        public NoteData() {
            this.idField = 0;
            this.descriptionField = "";
            this.employeeIdField = -1;
            this.dateAddedField = new System.DateTime(0);
            this.dateField = new System.DateTime(0);
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Subject {
            get {
                return this.subjectField;
            }
            set {
                this.subjectField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("")]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-1)]
        public int EmployeeId {
            get {
                return this.employeeIdField;
            }
            set {
                this.employeeIdField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(System.DateTime), "0001-01-01T00:00:00")]
        public System.DateTime DateAdded {
            get {
                return this.dateAddedField;
            }
            set {
                this.dateAddedField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(System.DateTime), "0001-01-01T00:00:00")]
        public System.DateTime Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        public long PersonId {
            get {
                return this.personIdField;
            }
            set {
                this.personIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public partial class PersonSearchParameters {
        
        private System.DateTime changedAfterField;
        
        private string consumerPersonNoField;
        
        private long customerIdField;
        
        private string emailField;
        
        private int employeeIdField;
        
        private bool getRelationDataField;
        
        private long idField;
        
        private TriState isEmployeeField;
        
        private string nameField;
        
        private string roleField;
        
        public PersonSearchParameters() {
            this.changedAfterField = new System.DateTime(0);
            this.customerIdField = ((long)(0));
            this.employeeIdField = 0;
            this.getRelationDataField = false;
            this.idField = ((long)(0));
            this.isEmployeeField = TriState.none;
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(System.DateTime), "0001-01-01T00:00:00")]
        public System.DateTime ChangedAfter {
            get {
                return this.changedAfterField;
            }
            set {
                this.changedAfterField = value;
            }
        }
        
        /// <remarks/>
        public string ConsumerPersonNo {
            get {
                return this.consumerPersonNoField;
            }
            set {
                this.consumerPersonNoField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(long), "0")]
        public long CustomerId {
            get {
                return this.customerIdField;
            }
            set {
                this.customerIdField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int EmployeeId {
            get {
                return this.employeeIdField;
            }
            set {
                this.employeeIdField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool GetRelationData {
            get {
                return this.getRelationDataField;
            }
            set {
                this.getRelationDataField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(long), "0")]
        public long Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(TriState.none)]
        public TriState IsEmployee {
            get {
                return this.isEmployeeField;
            }
            set {
                this.isEmployeeField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Role {
            get {
                return this.roleField;
            }
            set {
                this.roleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public enum TriState {
        
        /// <remarks/>
        none,
        
        /// <remarks/>
        True,
        
        /// <remarks/>
        False,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public partial class RelationData {
        
        private long contactIdField;
        
        private long customerIdField;
        
        private string emailField;
        
        private string mobileField;
        
        private string phoneField;
        
        private string titleField;
        
        /// <remarks/>
        public long ContactId {
            get {
                return this.contactIdField;
            }
            set {
                this.contactIdField = value;
            }
        }
        
        /// <remarks/>
        public long CustomerId {
            get {
                return this.customerIdField;
            }
            set {
                this.customerIdField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string Mobile {
            get {
                return this.mobileField;
            }
            set {
                this.mobileField = value;
            }
        }
        
        /// <remarks/>
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public partial class Address {
        
        private string cityField;
        
        private string countryField;
        
        private string countyField;
        
        private string descriptionField;
        
        private string postalAreaField;
        
        private string postalCodeField;
        
        private string stateField;
        
        private string streetField;
        
        private AddressType typeField;
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        public string County {
            get {
                return this.countyField;
            }
            set {
                this.countyField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string PostalArea {
            get {
                return this.postalAreaField;
            }
            set {
                this.postalAreaField = value;
            }
        }
        
        /// <remarks/>
        public string PostalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
            }
        }
        
        /// <remarks/>
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public string Street {
            get {
                return this.streetField;
            }
            set {
                this.streetField = value;
            }
        }
        
        /// <remarks/>
        public AddressType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public enum AddressType {
        
        /// <remarks/>
        Post,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public partial class PhoneNumber {
        
        private string descriptionField;
        
        private PhoneNumberType typeField;
        
        private string valueField;
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public PhoneNumberType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public enum PhoneNumberType {
        
        /// <remarks/>
        Primary,
        
        /// <remarks/>
        Mobile,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public partial class FaxNumber {
        
        private string descriptionField;
        
        private FaxNumberType typeField;
        
        private string valueField;
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public FaxNumberType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public enum FaxNumberType {
        
        /// <remarks/>
        Primary,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public partial class EmailAddress {
        
        private string descriptionField;
        
        private EmailAddressType typeField;
        
        private string valueField;
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public EmailAddressType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public enum EmailAddressType {
        
        /// <remarks/>
        Home,
        
        /// <remarks/>
        Primary,
        
        /// <remarks/>
        Alternative,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public partial class PersonItem {
        
        private string commentField;
        
        private string consumerPersonNoField;
        
        private string countryField;
        
        private int customerIdField;
        
        private System.DateTime dateChangedField;
        
        private System.DateTime dateOfBirthField;
        
        private string departmentField;
        
        private EmailAddress[] emailAddressesField;
        
        private int employeeNumberField;
        
        private FaxNumber faxNumberField;
        
        private string firstNameField;
        
        private Gender genderField;
        
        private long idField;
        
        private string lastNameField;
        
        private string nicknameField;
        
        private string personalStatusField;
        
        private PhoneNumber[] phoneNumbersField;
        
        private Address postAddressField;
        
        private RelationData[] relationDataField;
        
        private string urlField;
        
        private string webPasswordField;
        
        private string webUserNameField;
        
        private string workplaceField;
        
        private string workPositionField;
        
        private System.Nullable<bool> isPrivateField;
        
        private bool isPrivateFieldSpecified;
        
        private int employeeIdField;
        
        public PersonItem() {
            this.customerIdField = -2147483648;
            this.dateChangedField = new System.DateTime(0);
            this.dateOfBirthField = new System.DateTime(0);
            this.employeeNumberField = -2147483648;
            this.genderField = Gender.NoChange;
            this.idField = ((long)(0));
            this.employeeIdField = -2147483648;
        }
        
        /// <remarks/>
        public string Comment {
            get {
                return this.commentField;
            }
            set {
                this.commentField = value;
            }
        }
        
        /// <remarks/>
        public string ConsumerPersonNo {
            get {
                return this.consumerPersonNoField;
            }
            set {
                this.consumerPersonNoField = value;
            }
        }
        
        /// <remarks/>
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int CustomerId {
            get {
                return this.customerIdField;
            }
            set {
                this.customerIdField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(System.DateTime), "0001-01-01T00:00:00")]
        public System.DateTime DateChanged {
            get {
                return this.dateChangedField;
            }
            set {
                this.dateChangedField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(System.DateTime), "0001-01-01T00:00:00")]
        public System.DateTime DateOfBirth {
            get {
                return this.dateOfBirthField;
            }
            set {
                this.dateOfBirthField = value;
            }
        }
        
        /// <remarks/>
        public string Department {
            get {
                return this.departmentField;
            }
            set {
                this.departmentField = value;
            }
        }
        
        /// <remarks/>
        public EmailAddress[] EmailAddresses {
            get {
                return this.emailAddressesField;
            }
            set {
                this.emailAddressesField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int EmployeeNumber {
            get {
                return this.employeeNumberField;
            }
            set {
                this.employeeNumberField = value;
            }
        }
        
        /// <remarks/>
        public FaxNumber FaxNumber {
            get {
                return this.faxNumberField;
            }
            set {
                this.faxNumberField = value;
            }
        }
        
        /// <remarks/>
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(Gender.NoChange)]
        public Gender Gender {
            get {
                return this.genderField;
            }
            set {
                this.genderField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(long), "0")]
        public long Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        public string Nickname {
            get {
                return this.nicknameField;
            }
            set {
                this.nicknameField = value;
            }
        }
        
        /// <remarks/>
        public string PersonalStatus {
            get {
                return this.personalStatusField;
            }
            set {
                this.personalStatusField = value;
            }
        }
        
        /// <remarks/>
        public PhoneNumber[] PhoneNumbers {
            get {
                return this.phoneNumbersField;
            }
            set {
                this.phoneNumbersField = value;
            }
        }
        
        /// <remarks/>
        public Address PostAddress {
            get {
                return this.postAddressField;
            }
            set {
                this.postAddressField = value;
            }
        }
        
        /// <remarks/>
        public RelationData[] RelationData {
            get {
                return this.relationDataField;
            }
            set {
                this.relationDataField = value;
            }
        }
        
        /// <remarks/>
        public string Url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
        
        /// <remarks/>
        public string WebPassword {
            get {
                return this.webPasswordField;
            }
            set {
                this.webPasswordField = value;
            }
        }
        
        /// <remarks/>
        public string WebUserName {
            get {
                return this.webUserNameField;
            }
            set {
                this.webUserNameField = value;
            }
        }
        
        /// <remarks/>
        public string Workplace {
            get {
                return this.workplaceField;
            }
            set {
                this.workplaceField = value;
            }
        }
        
        /// <remarks/>
        public string WorkPosition {
            get {
                return this.workPositionField;
            }
            set {
                this.workPositionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> IsPrivate {
            get {
                return this.isPrivateField;
            }
            set {
                this.isPrivateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsPrivateSpecified {
            get {
                return this.isPrivateFieldSpecified;
            }
            set {
                this.isPrivateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int EmployeeId {
            get {
                return this.employeeIdField;
            }
            set {
                this.employeeIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public enum Gender {
        
        /// <remarks/>
        NoChange,
        
        /// <remarks/>
        Unknown,
        
        /// <remarks/>
        Female,
        
        /// <remarks/>
        Male,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetPersonIdCompletedEventHandler(object sender, GetPersonIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPersonIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPersonIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public long Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((long)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void SavePersonCompletedEventHandler(object sender, SavePersonCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SavePersonCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SavePersonCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public long Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((long)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetPersonIdsByUserNameCompletedEventHandler(object sender, GetPersonIdsByUserNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPersonIdsByUserNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPersonIdsByUserNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public long[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((long[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetPersonIdByCompanyIdCompletedEventHandler(object sender, GetPersonIdByCompanyIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPersonIdByCompanyIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPersonIdByCompanyIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public long Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((long)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetPersonsCompletedEventHandler(object sender, GetPersonsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPersonsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPersonsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PersonItem[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PersonItem[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetPersonsDetailedCompletedEventHandler(object sender, GetPersonsDetailedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPersonsDetailedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPersonsDetailedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PersonItem[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PersonItem[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void MakeRelationCompletedEventHandler(object sender, MakeRelationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MakeRelationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MakeRelationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetRelationsCompletedEventHandler(object sender, GetRelationsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRelationsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRelationsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RelationData[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RelationData[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetRelationsChangedAfterCompletedEventHandler(object sender, GetRelationsChangedAfterCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRelationsChangedAfterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRelationsChangedAfterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RelationData[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RelationData[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void DeleteRelationCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetNotesCompletedEventHandler(object sender, GetNotesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetNotesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetNotesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public NoteData[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((NoteData[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetAllNotesCompletedEventHandler(object sender, GetAllNotesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllNotesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllNotesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public NoteData[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((NoteData[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void AddNoteCompletedEventHandler(object sender, AddNoteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddNoteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddNoteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void DeleteNoteCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void DeleteNoteByIdCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetCategoryListCompletedEventHandler(object sender, GetCategoryListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCategoryListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCategoryListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Category[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Category[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetPersonCategoryListCompletedEventHandler(object sender, GetPersonCategoryListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPersonCategoryListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPersonCategoryListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void AddCategoryToPersonCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void RemoveCategoryFromPersonCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591