//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace in24seven.productRef {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ProductServiceSoap", Namespace="http://24sevenOffice.com/webservices")]
    public partial class ProductService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SetStockQuantityOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetProductsOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveProductsOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteProductsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPriceListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllPriceListsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCategoriesOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveCategoriesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDiscountMatrixPriceGroupOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDiscountMatrixCategoryOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ProductService() {
            this.Url = global::in24seven.Properties.Settings.Default.in24seven_productRef_ProductService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SetStockQuantityCompletedEventHandler SetStockQuantityCompleted;
        
        /// <remarks/>
        public event GetProductsCompletedEventHandler GetProductsCompleted;
        
        /// <remarks/>
        public event SaveProductsCompletedEventHandler SaveProductsCompleted;
        
        /// <remarks/>
        public event DeleteProductsCompletedEventHandler DeleteProductsCompleted;
        
        /// <remarks/>
        public event GetPriceListCompletedEventHandler GetPriceListCompleted;
        
        /// <remarks/>
        public event GetAllPriceListsCompletedEventHandler GetAllPriceListsCompleted;
        
        /// <remarks/>
        public event GetCategoriesCompletedEventHandler GetCategoriesCompleted;
        
        /// <remarks/>
        public event SaveCategoriesCompletedEventHandler SaveCategoriesCompleted;
        
        /// <remarks/>
        public event GetDiscountMatrixPriceGroupCompletedEventHandler GetDiscountMatrixPriceGroupCompleted;
        
        /// <remarks/>
        public event GetDiscountMatrixCategoryCompletedEventHandler GetDiscountMatrixCategoryCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://24sevenOffice.com/webservices/SetStockQuantity", RequestNamespace="http://24sevenOffice.com/webservices", ResponseNamespace="http://24sevenOffice.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SetStockQuantity(int productId, decimal stockQuantity) {
            object[] results = this.Invoke("SetStockQuantity", new object[] {
                        productId,
                        stockQuantity});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SetStockQuantityAsync(int productId, decimal stockQuantity) {
            this.SetStockQuantityAsync(productId, stockQuantity, null);
        }
        
        /// <remarks/>
        public void SetStockQuantityAsync(int productId, decimal stockQuantity, object userState) {
            if ((this.SetStockQuantityOperationCompleted == null)) {
                this.SetStockQuantityOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetStockQuantityOperationCompleted);
            }
            this.InvokeAsync("SetStockQuantity", new object[] {
                        productId,
                        stockQuantity}, this.SetStockQuantityOperationCompleted, userState);
        }
        
        private void OnSetStockQuantityOperationCompleted(object arg) {
            if ((this.SetStockQuantityCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetStockQuantityCompleted(this, new SetStockQuantityCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://24sevenOffice.com/webservices/GetProducts", RequestNamespace="http://24sevenOffice.com/webservices", ResponseNamespace="http://24sevenOffice.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Product[] GetProducts(ProductSearchParameters searchParams, string[] returnProperties) {
            object[] results = this.Invoke("GetProducts", new object[] {
                        searchParams,
                        returnProperties});
            return ((Product[])(results[0]));
        }
        
        /// <remarks/>
        public void GetProductsAsync(ProductSearchParameters searchParams, string[] returnProperties) {
            this.GetProductsAsync(searchParams, returnProperties, null);
        }
        
        /// <remarks/>
        public void GetProductsAsync(ProductSearchParameters searchParams, string[] returnProperties, object userState) {
            if ((this.GetProductsOperationCompleted == null)) {
                this.GetProductsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProductsOperationCompleted);
            }
            this.InvokeAsync("GetProducts", new object[] {
                        searchParams,
                        returnProperties}, this.GetProductsOperationCompleted, userState);
        }
        
        private void OnGetProductsOperationCompleted(object arg) {
            if ((this.GetProductsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetProductsCompleted(this, new GetProductsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://24sevenOffice.com/webservices/SaveProducts", RequestNamespace="http://24sevenOffice.com/webservices", ResponseNamespace="http://24sevenOffice.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Product[] SaveProducts(Product[] products) {
            object[] results = this.Invoke("SaveProducts", new object[] {
                        products});
            return ((Product[])(results[0]));
        }
        
        /// <remarks/>
        public void SaveProductsAsync(Product[] products) {
            this.SaveProductsAsync(products, null);
        }
        
        /// <remarks/>
        public void SaveProductsAsync(Product[] products, object userState) {
            if ((this.SaveProductsOperationCompleted == null)) {
                this.SaveProductsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveProductsOperationCompleted);
            }
            this.InvokeAsync("SaveProducts", new object[] {
                        products}, this.SaveProductsOperationCompleted, userState);
        }
        
        private void OnSaveProductsOperationCompleted(object arg) {
            if ((this.SaveProductsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveProductsCompleted(this, new SaveProductsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://24sevenOffice.com/webservices/DeleteProducts", RequestNamespace="http://24sevenOffice.com/webservices", ResponseNamespace="http://24sevenOffice.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Product[] DeleteProducts(Product[] products) {
            object[] results = this.Invoke("DeleteProducts", new object[] {
                        products});
            return ((Product[])(results[0]));
        }
        
        /// <remarks/>
        public void DeleteProductsAsync(Product[] products) {
            this.DeleteProductsAsync(products, null);
        }
        
        /// <remarks/>
        public void DeleteProductsAsync(Product[] products, object userState) {
            if ((this.DeleteProductsOperationCompleted == null)) {
                this.DeleteProductsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteProductsOperationCompleted);
            }
            this.InvokeAsync("DeleteProducts", new object[] {
                        products}, this.DeleteProductsOperationCompleted, userState);
        }
        
        private void OnDeleteProductsOperationCompleted(object arg) {
            if ((this.DeleteProductsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteProductsCompleted(this, new DeleteProductsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://24sevenOffice.com/webservices/GetPriceList", RequestNamespace="http://24sevenOffice.com/webservices", ResponseNamespace="http://24sevenOffice.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public KeyValuePair[] GetPriceList(int priceListId) {
            object[] results = this.Invoke("GetPriceList", new object[] {
                        priceListId});
            return ((KeyValuePair[])(results[0]));
        }
        
        /// <remarks/>
        public void GetPriceListAsync(int priceListId) {
            this.GetPriceListAsync(priceListId, null);
        }
        
        /// <remarks/>
        public void GetPriceListAsync(int priceListId, object userState) {
            if ((this.GetPriceListOperationCompleted == null)) {
                this.GetPriceListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPriceListOperationCompleted);
            }
            this.InvokeAsync("GetPriceList", new object[] {
                        priceListId}, this.GetPriceListOperationCompleted, userState);
        }
        
        private void OnGetPriceListOperationCompleted(object arg) {
            if ((this.GetPriceListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPriceListCompleted(this, new GetPriceListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://24sevenOffice.com/webservices/GetAllPriceLists", RequestNamespace="http://24sevenOffice.com/webservices", ResponseNamespace="http://24sevenOffice.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ProductPriceList[] GetAllPriceLists() {
            object[] results = this.Invoke("GetAllPriceLists", new object[0]);
            return ((ProductPriceList[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllPriceListsAsync() {
            this.GetAllPriceListsAsync(null);
        }
        
        /// <remarks/>
        public void GetAllPriceListsAsync(object userState) {
            if ((this.GetAllPriceListsOperationCompleted == null)) {
                this.GetAllPriceListsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllPriceListsOperationCompleted);
            }
            this.InvokeAsync("GetAllPriceLists", new object[0], this.GetAllPriceListsOperationCompleted, userState);
        }
        
        private void OnGetAllPriceListsOperationCompleted(object arg) {
            if ((this.GetAllPriceListsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllPriceListsCompleted(this, new GetAllPriceListsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://24sevenOffice.com/webservices/GetCategories", RequestNamespace="http://24sevenOffice.com/webservices", ResponseNamespace="http://24sevenOffice.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Category[] GetCategories(string[] returnProperties) {
            object[] results = this.Invoke("GetCategories", new object[] {
                        returnProperties});
            return ((Category[])(results[0]));
        }
        
        /// <remarks/>
        public void GetCategoriesAsync(string[] returnProperties) {
            this.GetCategoriesAsync(returnProperties, null);
        }
        
        /// <remarks/>
        public void GetCategoriesAsync(string[] returnProperties, object userState) {
            if ((this.GetCategoriesOperationCompleted == null)) {
                this.GetCategoriesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCategoriesOperationCompleted);
            }
            this.InvokeAsync("GetCategories", new object[] {
                        returnProperties}, this.GetCategoriesOperationCompleted, userState);
        }
        
        private void OnGetCategoriesOperationCompleted(object arg) {
            if ((this.GetCategoriesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCategoriesCompleted(this, new GetCategoriesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://24sevenOffice.com/webservices/SaveCategories", RequestNamespace="http://24sevenOffice.com/webservices", ResponseNamespace="http://24sevenOffice.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Category[] SaveCategories(Category[] categories) {
            object[] results = this.Invoke("SaveCategories", new object[] {
                        categories});
            return ((Category[])(results[0]));
        }
        
        /// <remarks/>
        public void SaveCategoriesAsync(Category[] categories) {
            this.SaveCategoriesAsync(categories, null);
        }
        
        /// <remarks/>
        public void SaveCategoriesAsync(Category[] categories, object userState) {
            if ((this.SaveCategoriesOperationCompleted == null)) {
                this.SaveCategoriesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveCategoriesOperationCompleted);
            }
            this.InvokeAsync("SaveCategories", new object[] {
                        categories}, this.SaveCategoriesOperationCompleted, userState);
        }
        
        private void OnSaveCategoriesOperationCompleted(object arg) {
            if ((this.SaveCategoriesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveCategoriesCompleted(this, new SaveCategoriesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://24sevenOffice.com/webservices/GetDiscountMatrixPriceGroup", RequestNamespace="http://24sevenOffice.com/webservices", ResponseNamespace="http://24sevenOffice.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Discount[] GetDiscountMatrixPriceGroup() {
            object[] results = this.Invoke("GetDiscountMatrixPriceGroup", new object[0]);
            return ((Discount[])(results[0]));
        }
        
        /// <remarks/>
        public void GetDiscountMatrixPriceGroupAsync() {
            this.GetDiscountMatrixPriceGroupAsync(null);
        }
        
        /// <remarks/>
        public void GetDiscountMatrixPriceGroupAsync(object userState) {
            if ((this.GetDiscountMatrixPriceGroupOperationCompleted == null)) {
                this.GetDiscountMatrixPriceGroupOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDiscountMatrixPriceGroupOperationCompleted);
            }
            this.InvokeAsync("GetDiscountMatrixPriceGroup", new object[0], this.GetDiscountMatrixPriceGroupOperationCompleted, userState);
        }
        
        private void OnGetDiscountMatrixPriceGroupOperationCompleted(object arg) {
            if ((this.GetDiscountMatrixPriceGroupCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDiscountMatrixPriceGroupCompleted(this, new GetDiscountMatrixPriceGroupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://24sevenOffice.com/webservices/GetDiscountMatrixCategory", RequestNamespace="http://24sevenOffice.com/webservices", ResponseNamespace="http://24sevenOffice.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Discount[] GetDiscountMatrixCategory() {
            object[] results = this.Invoke("GetDiscountMatrixCategory", new object[0]);
            return ((Discount[])(results[0]));
        }
        
        /// <remarks/>
        public void GetDiscountMatrixCategoryAsync() {
            this.GetDiscountMatrixCategoryAsync(null);
        }
        
        /// <remarks/>
        public void GetDiscountMatrixCategoryAsync(object userState) {
            if ((this.GetDiscountMatrixCategoryOperationCompleted == null)) {
                this.GetDiscountMatrixCategoryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDiscountMatrixCategoryOperationCompleted);
            }
            this.InvokeAsync("GetDiscountMatrixCategory", new object[0], this.GetDiscountMatrixCategoryOperationCompleted, userState);
        }
        
        private void OnGetDiscountMatrixCategoryOperationCompleted(object arg) {
            if ((this.GetDiscountMatrixCategoryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDiscountMatrixCategoryCompleted(this, new GetDiscountMatrixCategoryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public partial class ProductSearchParameters {
        
        private int idField;
        
        private int categoryIdField;
        
        private string noField;
        
        private string eAN1Field;
        
        private string nameField;
        
        private decimal priceField;
        
        private System.DateTime dateChangedField;
        
        private int[] productIdsField;
        
        public ProductSearchParameters() {
            this.idField = -2147483648;
            this.categoryIdField = -2147483648;
            this.noField = "";
            this.eAN1Field = "";
            this.nameField = "";
            this.priceField = ((decimal)(-79228162514264337593543950335m));
            this.dateChangedField = new System.DateTime(0);
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int CategoryId {
            get {
                return this.categoryIdField;
            }
            set {
                this.categoryIdField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("")]
        public string No {
            get {
                return this.noField;
            }
            set {
                this.noField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("")]
        public string EAN1 {
            get {
                return this.eAN1Field;
            }
            set {
                this.eAN1Field = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("")]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "-79228162514264337593543950335")]
        public decimal Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(System.DateTime), "0001-01-01T00:00:00")]
        public System.DateTime DateChanged {
            get {
                return this.dateChangedField;
            }
            set {
                this.dateChangedField = value;
            }
        }
        
        /// <remarks/>
        public int[] ProductIds {
            get {
                return this.productIdsField;
            }
            set {
                this.productIdsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public partial class Discount {
        
        private int priceGroupIdField;
        
        private int categoryIdField;
        
        private int customerIdField;
        
        private decimal valueField;
        
        public Discount() {
            this.priceGroupIdField = -2147483648;
            this.categoryIdField = -2147483648;
            this.customerIdField = -2147483648;
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int PriceGroupId {
            get {
                return this.priceGroupIdField;
            }
            set {
                this.priceGroupIdField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int CategoryId {
            get {
                return this.categoryIdField;
            }
            set {
                this.categoryIdField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int CustomerId {
            get {
                return this.customerIdField;
            }
            set {
                this.customerIdField = value;
            }
        }
        
        /// <remarks/>
        public decimal Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public partial class Category {
        
        private int idField;
        
        private string nameField;
        
        private string noField;
        
        private int parentIdField;
        
        private APIException aPIExceptionField;
        
        public Category() {
            this.idField = -2147483648;
            this.nameField = "";
            this.noField = "";
            this.parentIdField = -2147483648;
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("")]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("")]
        public string No {
            get {
                return this.noField;
            }
            set {
                this.noField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int ParentId {
            get {
                return this.parentIdField;
            }
            set {
                this.parentIdField = value;
            }
        }
        
        /// <remarks/>
        public APIException APIException {
            get {
                return this.aPIExceptionField;
            }
            set {
                this.aPIExceptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public partial class APIException {
        
        private string typeField;
        
        private string messageField;
        
        private string stackTraceField;
        
        /// <remarks/>
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public string StackTrace {
            get {
                return this.stackTraceField;
            }
            set {
                this.stackTraceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public partial class ProductPriceList {
        
        private int idField;
        
        private string nameField;
        
        private bool incVatField;
        
        private string currencyField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public bool IncVat {
            get {
                return this.incVatField;
            }
            set {
                this.incVatField = value;
            }
        }
        
        /// <remarks/>
        public string Currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public partial class KeyValuePair {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public partial class Product {
        
        private double cashPriceIncTaxField;
        
        private decimal webPriceField;
        
        private int supplierIdField;
        
        private int idField;
        
        private string nameField;
        
        private decimal taxRateField;
        
        private decimal stockField;
        
        private int statusIdField;
        
        private int categoryIdField;
        
        private int priceGroupIDField;
        
        private decimal inPriceField;
        
        private string descriptionField;
        
        private string descriptionLongField;
        
        private decimal costField;
        
        private string eAN1Field;
        
        private decimal priceField;
        
        private string noField;
        
        private System.DateTime dateChangedField;
        
        private APIException aPIExceptionField;
        
        private decimal weightField;
        
        private decimal minimumStockField;
        
        private decimal orderProposalField;
        
        private string stockLocationField;
        
        private string supplierProductCodeField;
        
        private string supplierProductNameField;
        
        private System.Nullable<bool> webField;
        
        private bool webFieldSpecified;
        
        private string productCodeField;
        
        private System.Nullable<bool> stockControlledField;
        
        private bool stockControlledFieldSpecified;
        
        private System.Nullable<bool> newOfferField;
        
        private bool newOfferFieldSpecified;
        
        private System.Nullable<bool> newProductField;
        
        private bool newProductFieldSpecified;
        
        public Product() {
            this.cashPriceIncTaxField = -1.7976931348623157E+308D;
            this.webPriceField = ((decimal)(-79228162514264337593543950335m));
            this.supplierIdField = -2147483648;
            this.idField = -2147483648;
            this.nameField = "";
            this.taxRateField = ((decimal)(-79228162514264337593543950335m));
            this.stockField = ((decimal)(-79228162514264337593543950335m));
            this.statusIdField = -2147483648;
            this.categoryIdField = -2147483648;
            this.priceGroupIDField = -2147483648;
            this.inPriceField = ((decimal)(-79228162514264337593543950335m));
            this.descriptionField = "";
            this.descriptionLongField = "";
            this.costField = ((decimal)(-79228162514264337593543950335m));
            this.eAN1Field = "";
            this.priceField = ((decimal)(-79228162514264337593543950335m));
            this.noField = "";
            this.dateChangedField = new System.DateTime(0);
            this.weightField = ((decimal)(-79228162514264337593543950335m));
            this.minimumStockField = ((decimal)(-79228162514264337593543950335m));
            this.orderProposalField = ((decimal)(-79228162514264337593543950335m));
            this.stockLocationField = "";
            this.supplierProductCodeField = "";
            this.supplierProductNameField = "";
            this.productCodeField = "";
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-1.7976931348623157E+308D)]
        public double CashPriceIncTax {
            get {
                return this.cashPriceIncTaxField;
            }
            set {
                this.cashPriceIncTaxField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "-79228162514264337593543950335")]
        public decimal WebPrice {
            get {
                return this.webPriceField;
            }
            set {
                this.webPriceField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int SupplierId {
            get {
                return this.supplierIdField;
            }
            set {
                this.supplierIdField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("")]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "-79228162514264337593543950335")]
        public decimal TaxRate {
            get {
                return this.taxRateField;
            }
            set {
                this.taxRateField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "-79228162514264337593543950335")]
        public decimal Stock {
            get {
                return this.stockField;
            }
            set {
                this.stockField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int StatusId {
            get {
                return this.statusIdField;
            }
            set {
                this.statusIdField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int CategoryId {
            get {
                return this.categoryIdField;
            }
            set {
                this.categoryIdField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int PriceGroupID {
            get {
                return this.priceGroupIDField;
            }
            set {
                this.priceGroupIDField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "-79228162514264337593543950335")]
        public decimal InPrice {
            get {
                return this.inPriceField;
            }
            set {
                this.inPriceField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("")]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("")]
        public string DescriptionLong {
            get {
                return this.descriptionLongField;
            }
            set {
                this.descriptionLongField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "-79228162514264337593543950335")]
        public decimal Cost {
            get {
                return this.costField;
            }
            set {
                this.costField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("")]
        public string EAN1 {
            get {
                return this.eAN1Field;
            }
            set {
                this.eAN1Field = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "-79228162514264337593543950335")]
        public decimal Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("")]
        public string No {
            get {
                return this.noField;
            }
            set {
                this.noField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(System.DateTime), "0001-01-01T00:00:00")]
        public System.DateTime DateChanged {
            get {
                return this.dateChangedField;
            }
            set {
                this.dateChangedField = value;
            }
        }
        
        /// <remarks/>
        public APIException APIException {
            get {
                return this.aPIExceptionField;
            }
            set {
                this.aPIExceptionField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "-79228162514264337593543950335")]
        public decimal Weight {
            get {
                return this.weightField;
            }
            set {
                this.weightField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "-79228162514264337593543950335")]
        public decimal MinimumStock {
            get {
                return this.minimumStockField;
            }
            set {
                this.minimumStockField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "-79228162514264337593543950335")]
        public decimal OrderProposal {
            get {
                return this.orderProposalField;
            }
            set {
                this.orderProposalField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("")]
        public string StockLocation {
            get {
                return this.stockLocationField;
            }
            set {
                this.stockLocationField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("")]
        public string SupplierProductCode {
            get {
                return this.supplierProductCodeField;
            }
            set {
                this.supplierProductCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("")]
        public string SupplierProductName {
            get {
                return this.supplierProductNameField;
            }
            set {
                this.supplierProductNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> Web {
            get {
                return this.webField;
            }
            set {
                this.webField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WebSpecified {
            get {
                return this.webFieldSpecified;
            }
            set {
                this.webFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("")]
        public string ProductCode {
            get {
                return this.productCodeField;
            }
            set {
                this.productCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> StockControlled {
            get {
                return this.stockControlledField;
            }
            set {
                this.stockControlledField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StockControlledSpecified {
            get {
                return this.stockControlledFieldSpecified;
            }
            set {
                this.stockControlledFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> NewOffer {
            get {
                return this.newOfferField;
            }
            set {
                this.newOfferField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NewOfferSpecified {
            get {
                return this.newOfferFieldSpecified;
            }
            set {
                this.newOfferFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> NewProduct {
            get {
                return this.newProductField;
            }
            set {
                this.newProductField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NewProductSpecified {
            get {
                return this.newProductFieldSpecified;
            }
            set {
                this.newProductFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void SetStockQuantityCompletedEventHandler(object sender, SetStockQuantityCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetStockQuantityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetStockQuantityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetProductsCompletedEventHandler(object sender, GetProductsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetProductsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetProductsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Product[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Product[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void SaveProductsCompletedEventHandler(object sender, SaveProductsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveProductsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveProductsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Product[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Product[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void DeleteProductsCompletedEventHandler(object sender, DeleteProductsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteProductsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteProductsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Product[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Product[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetPriceListCompletedEventHandler(object sender, GetPriceListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPriceListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPriceListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public KeyValuePair[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((KeyValuePair[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetAllPriceListsCompletedEventHandler(object sender, GetAllPriceListsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllPriceListsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllPriceListsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ProductPriceList[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ProductPriceList[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetCategoriesCompletedEventHandler(object sender, GetCategoriesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCategoriesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCategoriesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Category[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Category[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void SaveCategoriesCompletedEventHandler(object sender, SaveCategoriesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveCategoriesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveCategoriesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Category[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Category[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetDiscountMatrixPriceGroupCompletedEventHandler(object sender, GetDiscountMatrixPriceGroupCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDiscountMatrixPriceGroupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDiscountMatrixPriceGroupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Discount[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Discount[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetDiscountMatrixCategoryCompletedEventHandler(object sender, GetDiscountMatrixCategoryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDiscountMatrixCategoryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDiscountMatrixCategoryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Discount[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Discount[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591